import React from 'react';
import {ArrowLeft,ArrowRight,BookOpen,FlaskConical,ShieldCheck,Sparkles} from 'lucide-react';

const DATA={
 hu:{back:'Vissza a főoldalra',eye:'BEAUTY BY ILDY • TUDÁSTÁR',title:'Kozmetikai összetevők, érthetően.',lead:'Nem csak azt nézzük, mi szerepel az INCI-listán. Azt is, hogy milyen formában, milyen formulában, milyen koncentrációban — ha ismert — és milyen tudományos háttérrel kerül a bőrre.',updated:'Utoljára szakmailag frissítve: 2026. augusztus',how:'Hogyan értékelünk?',howText:'Az összetevő neve önmagában kevés. Külön vizsgáljuk a hatóanyag tudományos hátterét, a konkrét formula minőségét, az ismert koncentrációt, a tolerálhatóságot és azt, hogy van-e adat magáról a késztermékről.',labels:['MIT JELENT?','MIT TUDUNK RÓLA?','MIRE FIGYELÜNK?'],formula:'Formula térkép',formulaText:'A termékadatlapokon az INCI-t funkció szerint is szétszedjük: fő hatóanyagok • hidratálók • barrier-támogatók • nyugtatók • antioxidánsok • peptidek • lipidkomponensek • potenciálisan irritáló/érzékenyítő összetevők. A teljes INCI mindig külön, változtatás nélkül is megmarad.',rule:'Fontos szabály',ruleText:'Egy összetevő tudományos háttere nem bizonyítja automatikusan egy konkrét krém vagy szérum hatásosságát. A Beauty by Ildy ezért külön értékeli a hatóanyagot, a formulát és — ha rendelkezésre áll — a késztermék klinikai vizsgálatát.',sources:'Tudományos és hivatalos alapok',open:'FORRÁS MEGNYITÁSA'},
 en:{back:'Back to home',eye:'BEAUTY BY ILDY • KNOWLEDGE BASE',title:'Cosmetic ingredients, explained.',lead:'We look beyond the INCI list: form, formulation, concentration when disclosed, tolerability and the quality of scientific evidence.',updated:'Last scientifically reviewed: August 2026',how:'How do we assess ingredients?',howText:'An ingredient name alone is not enough. We assess ingredient-level evidence separately from formulation quality, known concentration, tolerability and finished-product evidence.',labels:['WHAT IS IT?','WHAT DO WE KNOW?','WHAT DO WE CHECK?'],formula:'Formula map',formulaText:'Product pages group the INCI by function: key actives • humectants • barrier support • soothing agents • antioxidants • peptides • lipids • potential irritants/sensitizers, while preserving the full original INCI separately.',rule:'Important rule',ruleText:'Evidence for an ingredient does not automatically prove the efficacy of a specific cream or serum. Beauty by Ildy evaluates the active, the formula and, where available, finished-product clinical evidence separately.',sources:'Scientific and official foundations',open:'OPEN SOURCE'},
 de:{back:'Zurück zur Startseite',eye:'BEAUTY BY ILDY • WISSENSBASIS',title:'Kosmetische Inhaltsstoffe, verständlich erklärt.',lead:'Wir betrachten mehr als die INCI-Liste: Form, Formulierung, bekannte Konzentration, Verträglichkeit und wissenschaftliche Evidenz.',updated:'Zuletzt wissenschaftlich geprüft: August 2026',how:'Wie bewerten wir?',howText:'Der Name eines Inhaltsstoffs allein reicht nicht. Wirkstoff-Evidenz, Formulierungsqualität, bekannte Konzentration, Verträglichkeit und Daten zum Fertigprodukt werden getrennt bewertet.',labels:['WAS IST DAS?','WAS WISSEN WIR?','WORAUF ACHTEN WIR?'],formula:'Formel-Landkarte',formulaText:'Auf Produktseiten ordnen wir die INCI nach Funktion: Hauptwirkstoffe • Feuchtigkeit • Barriereschutz • Beruhigung • Antioxidantien • Peptide • Lipide • potenzielle Reizstoffe. Die vollständige originale INCI bleibt separat erhalten.',rule:'Wichtige Regel',ruleText:'Die Evidenz eines Inhaltsstoffs beweist nicht automatisch die Wirksamkeit einer konkreten Creme oder eines Serums. Beauty by Ildy bewertet Wirkstoff, Formulierung und – falls vorhanden – klinische Daten des Fertigprodukts getrennt.',sources:'Wissenschaftliche und offizielle Grundlagen',open:'QUELLE ÖFFNEN'}
};

const ITEMS={
 hu:[
 ['Retinol & retinal','A-vitamin-származékok; a retinaldehid egy átalakulási lépéssel közelebb van a retinsavhoz, mint a retinol.','A retinoidok a photoaging legjobban kutatott kozmetikai hatóanyagcsoportjai közé tartoznak, de a késztermékek hatásossága nem egyforma.','Koncentráció, stabilitás, csomagolás, irritáció és a teljes formula.','ERŐSEBB TUDOMÁNYOS HÁTTÉR'],
 ['PDRN / Sodium DNA / Hydrolyzed DNA','DNS-eredetű polinukleotid-fragmentumok; kozmetikumokban Sodium DNA vagy Hydrolyzed DNA néven is megjelenhetnek.','A topikális PDRN bizonyítékai gyorsan fejlődnek, de egy adott PDRN-vizsgálat eredménye nem vihető át automatikusan minden PDRN-termékre.','Forrás, molekulaméret, koncentráció, delivery-rendszer és késztermék-vizsgálat.','ÍGÉRETES • TERMÉKFÜGGŐ'],
 ['Ceramidok','A szaruréteg természetes lipidjei; a barrier egyik kulcselemei.','Koleszterinnel és zsírsavakkal együtt fontos szerepük van a vízvesztés mérséklésében és a barrier szerkezetében.','Ceramidtípus, lipidkörnyezet és formulázás.','ERŐS BIOLÓGIAI ALAP'],
 ['Koleszterin & fitoszfingozin','A bőr barrierének természetes lipidkomponensei, amelyek gyakran ceramidok mellett jelennek meg.','Különösen barrier-helyreállító formulákban értékesek; az AESTURA-típusú lipidkomplexek miatt külön figyeljük őket.','Arányok, társított zsírsavak, ceramidok és a teljes emulzió.','BARRIER-KULCSKOMPONENSEK'],
 ['Szkvalán','Stabil, bőrbarát lipid és emolliens; a szkvalén hidrogénezett, stabilabb formája.','Segít csökkenteni a száraz érzetet és javítja a formula komfortját anélkül, hogy önmagában „anti-aging hatóanyag” lenne.','Forrás, textúra, komedogenitási egyéni hajlam és formula.','JÓL ISMERT EMOLLIENS'],
 ['Niacinamide','A B3-vitamin egyik formája.','Többféle bőrápolási célra használják, többek között barrier-, tónus- és faggyúközpontú formulákban.','Koncentráció, tolerálhatóság, társított hatóanyagok.','JÓL ISMERT HATÓANYAG'],
 ['Hialuronsav & többmolekulás HA','Természetesen is jelen lévő glükózaminoglikán; kozmetikumban főként vízmegkötő hidratáló.','A különböző HA-formák — például Sodium Hyaluronate, Hydrolyzed HA, crosspolymer — eltérő formulázási célt szolgálhatnak.','INCI-forma, molekulaméretre vonatkozó állítás és reális hatásígéret.','JÓL ISMERT • FORMULAFÜGGŐ'],
 ['Peptidek','Rövid aminosavláncok; nem egyetlen hatóanyagcsoportként értékeljük őket.','Tripeptide-1, Copper Tripeptide-1, Palmitoyl Pentapeptide-4, Acetyl Hexapeptide-8 és más peptidek mögött eltérő mennyiségű humán adat áll.','Pontos INCI-név, koncentráció, stabilitás, delivery és késztermék-adatok.','PEPTIDENKÉNT ÉRTÉKELENDŐ'],
 ['Panthenol','B5-provitamin; hidratáló és nyugtató formulák gyakori összetevője.','Barrier- és irritációcsökkentő célú készítményekben régóta használják; magasabb koncentrációban különösen érdekes.','Koncentráció, formula, érzékeny bőrön való tolerálhatóság.','JÓL ISMERT • BARRIER-TÁMOGATÓ'],
 ['Béta-glükán','Poliszacharid, amely hidratáló és nyugtató formulákban fordul elő.','A barrier- és komforttámogató szerep ígéretes, de a forrás és a molekuláris tulajdonságok számítanak.','Forrás, tisztaság, koncentráció és kész formula.','ÍGÉRETES KIEGÉSZÍTŐ'],
 ['Allantoin','Nyugtató, bőrkondicionáló összetevő.','Gyakori érzékeny bőrre szánt készítményekben és barrier-formulákban.','Koncentráció és a formula többi irritáló/nyugtató komponense.','JÓL ISMERT NYUGTATÓ'],
 ['Adenozin','Nukleozid, amely koreai kozmetikumokban gyakori funkcionális anti-wrinkle összetevő.','Kozmetikai ráncápolásban használják, de az eredményt mindig a kész formula és a termékteszt alapján értékeljük.','Koncentráció, társított peptidek/retinoidok és késztermék-adatok.','KOREAI FUNKCIONÁLIS HATÓANYAG'],
 ['NAD+ / Nicotinamide Adenine Dinucleotide','A sejtek energia-anyagcseréjében központi szerepű koenzim.','A longevity területén intenzíven kutatott molekula, de a topikális kozmetikai NAD+ bizonyítéka jóval korábbi fázisban van, mint a marketingje.','Stabilitás, bőrbe jutás, koncentráció és független humán vizsgálatok.','KORAI KUTATÁSI TERÜLET'],
 ['Glutation','Endogén antioxidáns tripeptid.','Kozmetikumokban antioxidáns és bőrtónus-egységesítő állításokkal használják; topikális hatása formula- és stabilitásfüggő.','Stabilitás, koncentráció, oxidációvédelem és késztermék-vizsgálat.','ÍGÉRETES • FORMULAFÜGGŐ'],
 ['Centella asiatica / CICA','Ázsiai gázló; kivonatként és izolált komponensekkel is megjelenhet, például asiaticoside, madecassic acid, asiatic acid.','Nyugtató és barrier-támogató formulák gyakori összetevője.','Kivonat típusa, aktív komponensek, százalék ha közölt.','FORMULAFÜGGŐ'],
 ['Ginzeng / ginszenozidok','Panax ginseng kivonatok és ginszenozid-származékok; prémium koreai age-well formulák jellegzetes összetevői.','Antioxidáns, barrier- és bőröregedési mechanizmusokkal kapcsolatban vizsgált növényi hatóanyagcsalád, de a késztermék-adatok külön értékelendők.','Kivonat típusa, standardizálás, mennyiség, illatanyagok és klinikai adatok.','ÍGÉRETES • PRÉMIUM K-BEAUTY'],
 ['C-vitamin-származékok','Az aszkorbinsav stabilabb vagy lipofilebb származékai, például Ascorbyl Tetraisopalmitate.','Antioxidáns és tónusjavító formulákban használják; a származék nem egyenlő automatikusan az L-aszkorbinsav bizonyítékaival.','Pontos forma, koncentráció, stabilitás és formula.','FORMÁNKÉNT ÉRTÉKELENDŐ'],
 ['Exoszómák / extracelluláris vezikulák','Sejtek által kibocsátott apró membránhólyagok; a kozmetikai „exoszóma” megnevezés nem mindig jelent azonos, jól karakterizált anyagot.','2026-ban továbbra is ígéretes, de heterogén és korlátozott humán bizonyítékú terület.','Forrás, karakterizálás, stabilitás, biztonság és humán vizsgálatok.','KORAI / ÍGÉRETES KUTATÁS'],
 ['Spicule / mikrotűszerű részecskék','Apró, gyakran szivacseredetű tűszerű struktúrák, amelyeket delivery-koncepciókban használnak.','Nem azonosak a professzionális microneedlinggel; a marketing gyorsabban fejlődik, mint a független klinikai evidencia.','Irritáció, barrier állapot, más aktívokkal kombinálás és biztonsági adatok.','KORLÁTOZOTT BIZONYÍTÉK'],
 ['Aloe vera','Növényi kivonat, amelyet hidratáló és nyugtató gélekben gyakran nagy arányban használnak.','A komfortérzetet és hidratálást támogathatja, de az „aloe százalék” önmagában nem mondja meg a teljes formula minőségét.','Alkoholtartalom, illatanyag, tartósítórendszer és érzékeny bőr toleranciája.','JÓL ISMERT NYUGTATÓ'],
 ['Argánolaj','Argania Spinosa kernel oil; zsírsavakban és tokoferolokban gazdag növényi olaj.','Hajápolásban elsősorban emolliens, fényt és simább érzetet adó komponens.','Mennyisége a formulában, szilikonokkal való kombináció és hajtípus.','HAJÁPOLÁSI EMOLLIENS'],
 ['Acmella oleracea / BOTALIX-típusú komplexek','Az Acmella oleracea növényi kivonatot gyakran „botox-like” vagy ráncsimító marketinggel használják.','Vannak mechanisztikus és kisebb vizsgálatok, de nem tekintjük a botulinum toxin kozmetikai megfelelőjének.','Pontos komplex, koncentráció, független humán adat és a késztermék formula.','MARKETINGÁLLÍTÁS KÜLÖN ELLENŐRIZENDŐ'],
 ['EGF / sh-Oligopeptide-1','Epidermal Growth Factorhoz kapcsolódó rekombináns peptid megnevezés, amely egyes regeneráló formulákban jelenik meg.','Biológiailag aktív jelátviteli molekulák kozmetikai használata érdekes, de stabilitásuk és ép bőrön való penetrációjuk kritikus kérdés.','Forrás, stabilitás, koncentráció, delivery és szabályozási státusz.','ÍGÉRETES • TECHNIKAILAG KÉNYES']
 ],
 en:[
 ['Retinol & retinal','Vitamin A derivatives; retinaldehyde is one conversion step closer to retinoic acid than retinol.','Retinoids are among the better-studied cosmetic ingredient families for photoaging, but finished-product efficacy varies.','Concentration, stability, packaging, irritation and full formula.','STRONGER SCIENTIFIC BASE'],
 ['PDRN / Sodium DNA / Hydrolyzed DNA','DNA-derived polynucleotide fragments used under several INCI names.','Topical evidence is developing rapidly, but one PDRN study cannot be generalized to every PDRN product.','Source, molecular size, concentration, delivery and finished-product evidence.','PROMISING • PRODUCT-DEPENDENT'],
 ['Ceramides','Natural stratum-corneum lipids and key components of the skin barrier.','They work with cholesterol and fatty acids to support barrier structure and reduce water loss.','Ceramide type, lipid environment and formulation.','STRONG BIOLOGICAL BASIS'],
 ['Cholesterol & phytosphingosine','Natural skin-barrier lipid components often paired with ceramides.','Especially relevant in barrier-repair formulas.','Ratios, companion fatty acids, ceramides and emulsion structure.','KEY BARRIER COMPONENTS'],
 ['Squalane','A stable, skin-compatible lipid and emollient.','Helps reduce dryness and improves formula comfort without being an anti-aging active by itself.','Source, texture, individual comedogenic tendency and formula.','WELL-KNOWN EMOLLIENT'],
 ['Niacinamide','A form of vitamin B3.','Used across barrier, tone and sebum-focused formulas.','Concentration, tolerability and companion actives.','WELL-KNOWN ACTIVE'],
 ['Hyaluronic acid & multi-weight HA','A naturally occurring glycosaminoglycan used mainly as a humectant.','Different forms such as Sodium Hyaluronate, Hydrolyzed HA and crosspolymers can serve different formulation goals.','INCI form, molecular-weight claims and realistic outcomes.','WELL-KNOWN • FORMULA-DEPENDENT'],
 ['Peptides','Short amino-acid chains; we do not evaluate them as one single active category.','Tripeptide-1, Copper Tripeptide-1, Palmitoyl Pentapeptide-4, Acetyl Hexapeptide-8 and others have different levels of evidence.','Exact INCI, concentration, stability, delivery and product data.','ASSESS PEPTIDE BY PEPTIDE'],
 ['Panthenol','Pro-vitamin B5 used in hydrating and soothing formulas.','Long used in barrier-supportive and irritation-calming skincare.','Concentration, formula and sensitive-skin tolerability.','WELL-KNOWN • BARRIER SUPPORT'],
 ['Beta-glucan','A polysaccharide used in hydrating and soothing formulas.','Barrier and comfort benefits are promising, with source and molecular characteristics mattering.','Source, purity, concentration and full formula.','PROMISING SUPPORTIVE ACTIVE'],
 ['Allantoin','A soothing skin-conditioning ingredient.','Common in sensitive-skin and barrier formulas.','Concentration and balance of soothing versus irritating components.','WELL-KNOWN SOOTHER'],
 ['Adenosine','A nucleoside frequently used as a functional anti-wrinkle ingredient in Korean cosmetics.','Used in wrinkle-care formulations; finished-product evidence still matters.','Concentration, companion peptides/retinoids and product testing.','KOREAN FUNCTIONAL ACTIVE'],
 ['NAD+ / Nicotinamide Adenine Dinucleotide','A coenzyme central to cellular energy metabolism.','Intensively researched in longevity science, but topical cosmetic evidence is still early compared with marketing.','Stability, skin delivery, concentration and independent human studies.','EARLY RESEARCH AREA'],
 ['Glutathione','An endogenous antioxidant tripeptide.','Used for antioxidant and tone-evening claims; topical performance depends on stability and formula.','Stability, concentration, oxidation protection and product testing.','PROMISING • FORMULA-DEPENDENT'],
 ['Centella asiatica / CICA','A botanical used as extracts and isolated components such as asiaticoside and madecassic acid.','Common in soothing and barrier-support formulas.','Extract type, active components and disclosed percentage.','FORMULA-DEPENDENT'],
 ['Ginseng / ginsenosides','Panax ginseng extracts and ginsenoside-derived compounds common in premium Korean age-well formulas.','Studied for antioxidant, barrier and skin-aging pathways; finished-product evidence remains separate.','Extract type, standardisation, amount, fragrance and clinical data.','PROMISING • PREMIUM K-BEAUTY'],
 ['Vitamin C derivatives','Stabilised or lipophilic derivatives such as Ascorbyl Tetraisopalmitate.','Used in antioxidant and tone-focused formulas; derivative evidence is not automatically identical to L-ascorbic acid evidence.','Exact form, concentration, stability and formula.','ASSESS BY FORM'],
 ['Exosomes / extracellular vesicles','Small membrane-bound particles released by cells; marketed “exosomes” are not always equivalent or well characterised.','Still a promising but heterogeneous field with limited high-quality human evidence in 2026.','Source, characterisation, stability, safety and human trials.','EARLY / PROMISING RESEARCH'],
 ['Spicules','Tiny needle-like structures often used in delivery concepts.','Not equivalent to professional microneedling; marketing currently outpaces independent clinical evidence.','Irritation, barrier condition, active combinations and safety data.','LIMITED EVIDENCE'],
 ['Aloe vera','A botanical commonly used in soothing and hydrating gels.','May support comfort and hydration, but a high aloe percentage alone does not define formula quality.','Alcohol, fragrance, preservative system and sensitive-skin tolerability.','WELL-KNOWN SOOTHER'],
 ['Argan oil','Argania Spinosa kernel oil rich in fatty acids and tocopherols.','In hair care it mainly works as an emollient that improves shine and smooth feel.','Amount in formula, silicone combination and hair type.','HAIR-CARE EMOLLIENT'],
 ['Acmella oleracea / BOTALIX-type complexes','A botanical extract frequently marketed with “botox-like” or wrinkle-smoothing language.','Mechanistic and smaller studies exist, but it is not treated as a cosmetic equivalent of botulinum toxin.','Exact complex, concentration, independent human data and full formula.','MARKETING CLAIM NEEDS CHECKING'],
 ['EGF / sh-Oligopeptide-1','A recombinant peptide designation related to Epidermal Growth Factor.','Biologically active signalling molecules are interesting in skincare, but stability and penetration through intact skin are critical questions.','Source, stability, concentration, delivery and regulatory status.','PROMISING • TECHNICALLY COMPLEX']
 ],
 de:[
 ['Retinol & Retinal','Vitamin-A-Derivate; Retinaldehyd liegt einen Umwandlungsschritt näher an Retinsäure als Retinol.','Retinoide gehören zu den besser untersuchten Wirkstoffgruppen bei Photoaging, die Wirkung von Fertigprodukten variiert jedoch.','Konzentration, Stabilität, Verpackung, Reizung und Gesamtformel.','STÄRKERE WISSENSCHAFTLICHE BASIS'],
 ['PDRN / Sodium DNA / Hydrolyzed DNA','DNA-basierte Polynukleotid-Fragmente unter verschiedenen INCI-Bezeichnungen.','Die topische Evidenz entwickelt sich schnell, lässt sich aber nicht pauschal auf jedes PDRN-Produkt übertragen.','Quelle, Molekülgröße, Konzentration, Delivery und Produktdaten.','VIELVERSPRECHEND • PRODUKTABHÄNGIG'],
 ['Ceramide','Natürliche Lipide der Hornschicht und Schlüsselbestandteile der Hautbarriere.','Mit Cholesterin und Fettsäuren unterstützen sie die Barrierestruktur und reduzieren Wasserverlust.','Ceramidtyp, Lipidumgebung und Formulierung.','STARKE BIOLOGISCHE BASIS'],
 ['Cholesterin & Phytosphingosin','Natürliche Lipidkomponenten der Hautbarriere, oft zusammen mit Ceramiden eingesetzt.','Besonders relevant in Barrierereparatur-Formeln.','Verhältnis, Fettsäuren, Ceramide und Emulsionsstruktur.','SCHLÜSSELKOMPONENTEN DER BARRIERE'],
 ['Squalan','Stabiles, hautverträgliches Lipid und Emolliens.','Reduziert Trockenheitsgefühl und verbessert den Komfort der Formulierung.','Quelle, Textur, individuelle Verträglichkeit und Formel.','GUT BEKANNTES EMOLLIENS'],
 ['Niacinamid','Eine Form von Vitamin B3.','Wird in Barrier-, Tonus- und Sebum-orientierten Formeln eingesetzt.','Konzentration, Verträglichkeit und Begleitwirkstoffe.','GUT BEKANNTER WIRKSTOFF'],
 ['Hyaluronsäure & Multi-Weight-HA','Natürliches Glykosaminoglykan, vor allem als Feuchthaltemittel eingesetzt.','Verschiedene HA-Formen können unterschiedliche Formulierungsziele erfüllen.','INCI-Form, Molekülgrößen-Claims und realistische Wirkung.','GUT BEKANNT • FORMELABHÄNGIG'],
 ['Peptide','Kurze Aminosäureketten; keine einheitliche Wirkstoffklasse.','Tripeptide-1, Copper Tripeptide-1, Palmitoyl Pentapeptide-4, Acetyl Hexapeptide-8 und andere haben unterschiedliche Evidenz.','Exakte INCI, Konzentration, Stabilität, Delivery und Produktdaten.','PEPTID FÜR PEPTID BEWERTEN'],
 ['Panthenol','Provitamin B5 in feuchtigkeitsspendenden und beruhigenden Formeln.','Seit Langem in Barrier- und Sensitivpflege eingesetzt.','Konzentration, Formulierung und Verträglichkeit.','GUT BEKANNT • BARRIERESUPPORT'],
 ['Beta-Glucan','Polysaccharid in hydratisierenden und beruhigenden Formeln.','Barrier- und Komforteffekte sind vielversprechend.','Quelle, Reinheit, Konzentration und Gesamtformel.','VIELVERSPRECHENDER BEGLEITWIRKSTOFF'],
 ['Allantoin','Beruhigender, hautkonditionierender Inhaltsstoff.','Häufig in Sensitiv- und Barrierpflege.','Konzentration und Gesamtbalance der Formel.','GUT BEKANNTER BERUHIGER'],
 ['Adenosin','Nukleosid, das in koreanischer Kosmetik häufig als funktioneller Anti-Falten-Wirkstoff eingesetzt wird.','Wird in Faltenpflege verwendet; Daten zum Fertigprodukt bleiben wichtig.','Konzentration, Begleitpeptide/Retinoide und Produkttests.','KOREANISCHER FUNKTIONSWIRKSTOFF'],
 ['NAD+ / Nicotinamide Adenine Dinucleotide','Koenzym mit zentraler Rolle im zellulären Energiestoffwechsel.','In der Longevity-Forschung intensiv untersucht, topische Kosmetikevidenz ist jedoch noch früh.','Stabilität, Hautpenetration, Konzentration und unabhängige Humanstudien.','FRÜHES FORSCHUNGSFELD'],
 ['Glutathion','Endogenes antioxidatives Tripeptid.','Für antioxidative und tonusausgleichende Claims genutzt; die Wirkung hängt stark von Stabilität und Formel ab.','Stabilität, Konzentration, Oxidationsschutz und Produkttests.','VIELVERSPRECHEND • FORMELABHÄNGIG'],
 ['Centella asiatica / CICA','Botanischer Extrakt und isolierte Komponenten wie Asiaticosid und Madecassinsäure.','Häufig in beruhigenden und barrierestützenden Formeln.','Extraktart, aktive Komponenten und deklarierter Anteil.','FORMELABHÄNGIG'],
 ['Ginseng / Ginsenoside','Panax-ginseng-Extrakte und Ginsenosid-Derivate in hochwertiger koreanischer Age-Well-Pflege.','Für antioxidative, Barrier- und Hautalterungsmechanismen untersucht; Produktdaten werden getrennt bewertet.','Extraktart, Standardisierung, Menge, Duftstoffe und klinische Daten.','VIELVERSPRECHEND • PREMIUM K-BEAUTY'],
 ['Vitamin-C-Derivate','Stabilere oder lipophile Derivate wie Ascorbyl Tetraisopalmitate.','Für antioxidative und tonusausgleichende Formeln; nicht automatisch mit L-Ascorbinsäure gleichzusetzen.','Exakte Form, Konzentration, Stabilität und Formel.','NACH FORM BEWERTEN'],
 ['Exosomen / extrazelluläre Vesikel','Kleine membrangebundene Partikel; als „Exosomen“ vermarktete Materialien sind nicht immer gleichwertig charakterisiert.','2026 weiterhin vielversprechend, aber heterogen mit begrenzter hochwertiger Human-Evidenz.','Quelle, Charakterisierung, Stabilität, Sicherheit und Humanstudien.','FRÜHE / VIELVERSPRECHENDE FORSCHUNG'],
 ['Spicules','Kleine nadelartige Strukturen in bestimmten Delivery-Konzepten.','Nicht mit professionellem Microneedling gleichzusetzen; Marketing ist der unabhängigen Evidenz voraus.','Reizung, Barrierestatus, Wirkstoffkombinationen und Sicherheitsdaten.','BEGRENZTE EVIDENZ'],
 ['Aloe vera','Botanischer Extrakt in beruhigenden und hydratisierenden Gelen.','Kann Komfort und Hydratation unterstützen; ein hoher Aloe-Anteil allein bestimmt nicht die Formelqualität.','Alkohol, Duftstoffe, Konservierung und Sensitivhaut-Verträglichkeit.','GUT BEKANNTER BERUHIGER'],
 ['Arganöl','Argania-Spinosa-Kernöl, reich an Fettsäuren und Tocopherolen.','In Haarpflege vor allem als Emolliens für Glanz und glatteres Haargefühl.','Menge in der Formel, Silikonkombination und Haartyp.','HAARPFLEGE-EMOLLIENS'],
 ['Acmella oleracea / BOTALIX-Komplexe','Pflanzenextrakt, häufig mit „Botox-like“- oder glättender Sprache vermarktet.','Es gibt mechanistische und kleinere Studien, aber keine Gleichsetzung mit Botulinumtoxin.','Exakter Komplex, Konzentration, unabhängige Humandaten und Gesamtformel.','MARKETING-CLAIM PRÜFEN'],
 ['EGF / sh-Oligopeptide-1','Rekombinante Peptidbezeichnung im Zusammenhang mit Epidermal Growth Factor.','Biologisch aktive Signalmoleküle sind interessant, Stabilität und Penetration intakter Haut bleiben jedoch kritisch.','Quelle, Stabilität, Konzentration, Delivery und regulatorischer Status.','VIELVERSPRECHEND • TECHNISCH KOMPLEX']
 ]
};

const SOURCES=[
 ['2026','Skin aging: mechanisms, evaluation, and rejuvenation','https://pubmed.ncbi.nlm.nih.gov/42168603/'],
 ['2026','Topical and systemic skin aging interventions','https://pubmed.ncbi.nlm.nih.gov/41846007/'],
 ['2026','PDRN topical split-face human study','https://pubmed.ncbi.nlm.nih.gov/42430369/'],
 ['2026','Home-Based Dermatologic Devices: Evidence-Based Insights','https://pubmed.ncbi.nlm.nih.gov/42545315/'],
 ['OFFICIAL','AESTURA ATOBARRIER365 Cream – current INCI','https://int.aestura.com/products/atobarrier365-cream'],
 ['OFFICIAL','IOPE XMD Stem III Clinical Recovery Serum – current INCI','https://int.iope.com/products/xmd-stem-iii-clinical-recovery-serum'],
 ['OFFICIAL','Sulwhasoo Concentrated Ginseng Rejuvenating Cream – current INCI','https://int.sulwhasoo.com/products/concentrated-ginseng-rejuvenating-cream'],
 ['OFFICIAL','AXIS-Y Triple PDRN Barrier Boost Serum – current INCI','https://www.axis-y.com/products/triple-pdrn-barrier-boost-serum']
];

export function IngredientsPage({lang='hu'}){
 const t=DATA[lang]||DATA.hu;
 const items=ITEMS[lang]||ITEMS.hu;
 return <main className="ingredientsPage">
  <section className="ingredientHero"><div><a href="#top" className="guideBack"><ArrowLeft size={14}/>{t.back}</a><p className="eyebrow">{t.eye}</p><h1>{t.title}</h1><p className="ingredientLead">{t.lead}</p><p className="reviewed">{t.updated}</p></div></section>
  <section className="ingredientMethod"><FlaskConical size={25}/><div><h2>{t.how}</h2><p>{t.howText}</p></div></section>
  <section className="ingredientGrid">{items.map((it,i)=><article className="ingredientCard" key={it[0]}><div className="ingredientTop"><small>{String(i+1).padStart(2,'0')}</small><span>{it[4]}</span></div><h2>{it[0]}</h2><h3>{t.labels[0]}</h3><p>{it[1]}</p><h3>{t.labels[1]}</h3><p>{it[2]}</p><h3>{t.labels[2]}</h3><p>{it[3]}</p></article>)}</section>
  <section className="formulaMap"><div><Sparkles size={24}/><h2>{t.formula}</h2><p>{t.formulaText}</p></div><div><ShieldCheck size={24}/><h2>{t.rule}</h2><p>{t.ruleText}</p></div></section>
  <section className="ingredientSources"><div className="sourceHead"><BookOpen size={24}/><h2>{t.sources}</h2></div><div>{SOURCES.map(([year,title,url])=><article key={title}><small>{year}</small><h3>{title}</h3><a href={url} target="_blank" rel="noreferrer">{t.open}<ArrowRight size={13}/></a></article>)}</div></section>
 </main>
}
