import React from 'react';

const business={name:'Devecz Ildikó',address:'Hauptstraße 13, 8380 Jennersdorf, Austria',uid:'ATU78435757',gisa:'35410898',trade:'Büroservice',email:'travel.by.ildy@gmail.com'};

export const legalLabels={
 hu:{imprint:'Impresszum',privacy:'Adatkezelési tájékoztató',cookies:'Süti tájékoztató',terms:'Felhasználási feltételek',affiliate:'Affiliate nyilatkozat',health:'Egészségügyi és termékjogi nyilatkozat',back:'Vissza a főoldalra',updated:'Utolsó frissítés: 2026. augusztus'},
 en:{imprint:'Imprint',privacy:'Privacy Policy',cookies:'Cookie Policy',terms:'Terms of Use',affiliate:'Affiliate Disclosure',health:'Health & Product Disclaimer',back:'Back to homepage',updated:'Last updated: August 2026'},
 de:{imprint:'Impressum',privacy:'Datenschutzerklärung',cookies:'Cookie-Hinweis',terms:'Nutzungsbedingungen',affiliate:'Affiliate-Offenlegung',health:'Gesundheits- & Produkthinweis',back:'Zurück zur Startseite',updated:'Zuletzt aktualisiert: August 2026'}
};

const docs={
 hu:{
 imprint:{title:'Impresszum',sections:[
  ['A weboldal üzemeltetője és médiatulajdonosa',<>Márkanév / weboldal: <strong>Beauty by Ildy</strong><br/>Üzemeltető: <strong>{business.name}</strong><br/>Vállalkozási forma: egyéni vállalkozó (Ausztria)<br/>Székhely: {business.address}<br/>UID: {business.uid}<br/>GISA: {business.gisa}<br/>Bejegyzett Gewerbe: {business.trade}<br/>E-mail: <a href={`mailto:${business.email}`}>{business.email}</a></>],
  ['Gewerbe / szakmai adatok',<>Kamarai tagság: Wirtschaftskammer Burgenland (WKO). Illetékes Gewerbe-hatóság: Bezirkshauptmannschaft Jennersdorf, Hauptplatz 15, 8380 Jennersdorf, Austria. Alkalmazandó jog: osztrák Gewerbeordnung (GewO).</>],
  ['Közzététel az osztrák Mediengesetz alapján',<>Médiatulajdonos: Beauty by Ildy — {business.name}. Vállalkozási tevékenység: beauty-, wellness- és életmód-tartalomszolgáltatás, valamint affiliate marketing a bejegyzett vállalkozási tevékenység keretében. Szerkesztői irány: független, válogatott információk bőrápolásról, beauty technológiáról, haj- és fejbőrápolásról, wellnessről és kapcsolódó termékekről. A weboldalnak nincs politikai vagy világnézeti célja.</>],
  ['A szolgáltatás jellege',<>A Beauty by Ildy kereskedelmi célú szerkesztőségi és affiliate marketing weboldal. Nem saját webshopként működik: a kiválasztott termékek és eszközök megvásárlása jellemzően független partneroldalon történik. A vásárlási szerződés, fizetés, szállítás, visszaküldés, garancia és ügyfélszolgálat az adott partner feltételei szerint alakul.</>],
  ['Szerzői jog',<>A Beauty by Ildy saját szövegei, elrendezése és kreatív tartalmai szerzői jogi védelem alatt állnak. A harmadik felek nevei, védjegyei, képei, videói és termékanyagai a megfelelő jogosultak tulajdonában maradnak.</>]
 ]},
 privacy:{title:'Adatkezelési tájékoztató',sections:[
  ['1. Az adatkezelő adatai',<>Adatkezelő: <strong>{business.name}</strong>, ausztriai egyéni vállalkozó. Székhely: {business.address}. UID: {business.uid}. GISA: {business.gisa}. E-mail: <a href={`mailto:${business.email}`}>{business.email}</a>.</>],
  ['2. Technikai kiszolgálás',<>A weboldal technikai infrastruktúrája, tárhelye és kódtárolása külső szolgáltatókat vehet igénybe. Ezek a szolgáltatók a weboldal kiszolgálásához, biztonságához és hibakereséséhez szükséges technikai adatokat — például IP-címet, böngészőtípust, naplóadatokat — kezelhetnek saját adatvédelmi feltételeik szerint.</>],
  ['3. Kapcsolatfelvétel',<>Ha e-mailben kapcsolatba lépsz a Beauty by Ildyvel, az általad megadott adatokat — például nevet, e-mail-címet és üzenetet — a megkeresés megválaszolásához és üzleti kapcsolattartáshoz kezeljük. Jogalap lehet a GDPR 6. cikk (1) b) pontja vagy a 6. cikk (1) f) pontja.</>],
  ['4. Partner- és affiliate linkek',<>A Beauty by Ildy független márkákhoz és kereskedőkhöz vezető affiliate vagy ajánlói linkeket használhat. Ilyen partner lehet például Nu Skin, Neumi, illetve később más beauty-, beauty-tech- vagy wellness-szolgáltató. A partneroldal megnyitásakor az adott szolgáltató saját adatvédelmi szabályai alkalmazandók. A Beauty by Ildy a partneroldalon történő fizetést és rendelést nem kezeli.</>],
  ['5. Érintetti jogok',<>A GDPR alapján — az alkalmazandó feltételek szerint — kérhetsz hozzáférést, helyesbítést, törlést, korlátozást, adathordozhatóságot, tiltakozhatsz bizonyos adatkezelés ellen, és jogosult lehetsz panaszt tenni az illetékes adatvédelmi hatóságnál.</>],
  ['6. Megőrzés és módosítás',<>Az adatokat csak a szükséges ideig vagy a jogszabályban előírt megőrzési idő végéig kezeljük. A tájékoztató a weboldal funkcióinak, partnereinek vagy technikai infrastruktúrájának változásával frissülhet.</>]
 ]},
 cookies:{title:'Süti tájékoztató',sections:[
  ['1. Sütik és hasonló technológiák',<>A sütik és helyi böngészőtárolási megoldások kis adatállományok vagy technikai tárolási módszerek, amelyek beállítások megjegyzésére, biztonságra és funkciók biztosítására használhatók.</>],
  ['2. Jelenlegi működés',<>A Beauty by Ildy jelenlegi alapverziója nem aktivál szándékosan Google Analytics, Google Ads, Meta Pixel vagy más hirdetési követőkódot. Ha ez később változik, a tájékoztatót és — ahol szükséges — a hozzájárulási mechanizmust előbb frissítjük.</>],
  ['3. Partneroldalak és külső linkek',<>Affiliate vagy terméklinkre kattintva független partneroldalra juthatsz. A céloldal saját sütiket, affiliate követési paramétereket és hasonló technológiákat használhat. Ezekre a partner saját cookie- és adatvédelmi szabályai vonatkoznak.</>],
  ['4. Beágyazott külső technológiák',<>Ha később videó, értékelő widget, partnereszköz vagy más beágyazott külső tartalom kerül az oldalra, a szükségtelen technológiákat — ahol jogilag hozzájárulás szükséges — csak megfelelő hozzájárulás után aktiváljuk.</>],
  ['5. Böngészőbeállítások',<>A sütiket és helyi webhelyadatokat a böngésződ beállításaiban törölheted vagy korlátozhatod. Egyes funkciók működését ez befolyásolhatja.</>]
 ]},
 terms:{title:'Felhasználási feltételek',sections:[
  ['1. Üzemeltető és hatály',<>A Beauty by Ildy üzemeltetője {business.name}, ausztriai egyéni vállalkozó. E feltételek a weboldal szerkesztőségi beauty-, beauty-tech-, haj-, wellness- és affiliate tartalmainak használatára vonatkoznak.</>],
  ['2. Nem saját webshop',<>A Beauty by Ildy nem maga értékesíti és nem maga szállítja a partnertermékeket, kivéve, ha ezt egy adott ajánlatnál kifejezetten másként jelezzük. A partneroldalon létrejövő vásárlási szerződés közvetlenül a vásárló és az adott partner között jön létre.</>],
  ['3. Árak, elérhetőség és termékadatok',<>Az árak, készlet, csomagok, szállítási területek, akciók, összetevők és termékspecifikációk változhatnak. Vásárlás előtt mindig a partner végleges termékoldala és feltételei az irányadók.</>],
  ['4. Szerkesztői tartalom',<>A Beauty by Ildy célja a termékek és technológiák értelmezése, összehasonlítása és válogatása. A tartalom tájékoztató jellegű, nem garantál egyéni eredményt, és nem helyettesít szakember által adott személyre szabott orvosi, bőrgyógyászati, dietetikai vagy más egészségügyi tanácsot.</>],
  ['5. Külső szolgáltatók',<>A Beauty by Ildy nem ellenőrzi a független partneroldalak működését, készletét, szállítását vagy szerződéses teljesítését. Ez nem zár ki olyan felelősséget, amelyet kötelező jog alapján nem lehet kizárni.</>],
  ['6. Szellemi tulajdon',<>A saját tartalmak engedély nélküli kereskedelmi másolása, újraközlése vagy automatizált tömeges felhasználása nem megengedett. Harmadik fél védjegyei és anyagai a megfelelő jogosultak tulajdonában maradnak.</>]
 ]},
 affiliate:{title:'Affiliate nyilatkozat',sections:[
  ['1. Kereskedelmi affiliate tevékenység',<>A Beauty by Ildy kereskedelmi célú beauty-, beauty-tech- és wellness-tartalomplatform. Egyes gombok, termékajánlások és kimenő linkek affiliate, referral vagy más partneri hivatkozások lehetnek.</>],
  ['2. Hogyan működik a jutalék',<>Ha jogosult partnerlinken keresztül megfelelő vásárlás vagy más minősített tranzakció történik, a Beauty by Ildy jutalékot vagy más partneri díjazást kaphat. Ez jellemzően nem növeli a partner által a vásárlónak felszámított árat.</>],
  ['3. Partnerpéldák',<>Aktív vagy tervezett partneri kapcsolatok között szerepelhet Nu Skin, Neumi, HubisLab, Biodance, Aestura, NIRA, CurrentBody, Medicube, IOPE, Sulwhasoo, Genabelle és más szolgáltató. Egy márka megjelenése önmagában nem jelenti azt, hogy minden hozzá vezető link jutalékos.</>],
  ['4. Független válogatás',<>Az affiliate kapcsolat önmagában nem garantál pozitív értékelést vagy kiemelést. A Beauty by Ildy célja, hogy a válogatásnál a formula, technológia, biztonság, bizonyítékok és valódi felhasználói érték elsőbbséget élvezzen a jutalékkal szemben.</>],
  ['5. Ajándékba kapott teszttermékek',<>Ha egy terméket vagy eszközt tesztelésre ingyenesen kapunk, vagy fizetett együttműködés része, ezt a kapcsolódó tartalomnál egyértelműen jelöljük. Az ajándék vagy díjazás nem jelent automatikusan pozitív véleményt.</>]
 ]},
 health:{title:'Egészségügyi és termékjogi nyilatkozat',sections:[
  ['1. Nem orvosi tanács',<>A Beauty by Ildy tartalma tájékoztató és szerkesztőségi jellegű. Nem diagnosztizál, nem kezel betegséget, és nem helyettesíti orvos, bőrgyógyász, gyógyszerész, dietetikus vagy más képzett egészségügyi szakember személyre szabott tanácsát.</>],
  ['2. Kozmetikumok és beauty eszközök',<>Az eredmények személyenként eltérhetnek. Használat előtt olvasd el a gyártó utasításait, ellenjavallatait és biztonsági figyelmeztetéseit. Érzékeny bőr, bőrbetegség, terhesség, implantátum, gyógyszeres kezelés vagy más egészségi állapot esetén szükség lehet szakember véleményére.</>],
  ['3. Étrend-kiegészítők és wellness',<>Az étrend-kiegészítők nem helyettesítik a változatos, kiegyensúlyozott étrendet és az egészséges életmódot. Az oldalon szereplő wellness-tartalom nem állít betegséget megelőző, kezelő vagy gyógyító hatást, kivéve, ha ilyen állítás jogszerűen és megfelelően engedélyezett.</>],
  ['4. Márkaállítások és bizonyítékok',<>A gyártói klinikai vagy marketingállításokat igyekszünk egyértelműen elkülöníteni a független bizonyítékoktól. Egy gyártó által finanszírozott vagy kis mintás vizsgálat nem azonos bizonyító erejű egy nagy, független klinikai vizsgálattal.</>]
 ]}
 },
 en:{
 imprint:{title:'Imprint',sections:[['Website operator and media owner',<>Brand / website: <strong>Beauty by Ildy</strong><br/>Operator: <strong>{business.name}</strong><br/>Legal form: sole proprietor (Austria)<br/>Business address: {business.address}<br/>VAT ID: {business.uid}<br/>GISA: {business.gisa}<br/>Registered trade: {business.trade}<br/>Email: <a href={`mailto:${business.email}`}>{business.email}</a></>],['Trade-law information',<>Member of Wirtschaftskammer Burgenland (WKO). Competent authority: Bezirkshauptmannschaft Jennersdorf, Hauptplatz 15, 8380 Jennersdorf, Austria. Applicable trade law: Austrian Gewerbeordnung (GewO).</>],['Disclosure under the Austrian Media Act',<>Media owner: Beauty by Ildy — {business.name}. Business activity: beauty, wellness and lifestyle content and affiliate marketing within the registered business activity. Editorial direction: independent curated information about skincare, beauty technology, hair and scalp care, wellness and related products. No political or ideological objective.</>],['Nature of the service',<>Beauty by Ildy is a commercial editorial and affiliate-marketing website. It is not operated as its own webshop: purchases generally take place on independent partner websites, where the partner controls the contract, payment, delivery, returns, warranty and customer service.</>],['Copyright',<>Original Beauty by Ildy text, layout and creative content are protected by applicable copyright law. Third-party names, trademarks, images, video and product materials remain subject to their owners’ rights.</>]]},
 privacy:{title:'Privacy Policy',sections:[['1. Controller',<>Controller: <strong>{business.name}</strong>, sole proprietor in Austria. Address: {business.address}. VAT ID: {business.uid}. GISA: {business.gisa}. Email: <a href={`mailto:${business.email}`}>{business.email}</a>.</>],['2. Technical delivery',<>The site may use external infrastructure, hosting and code-repository providers. They may process technical data such as IP address, browser type and security logs as necessary to deliver and protect the site under their own privacy terms.</>],['3. Contact enquiries',<>If you contact Beauty by Ildy by email, we process the data you provide to answer the enquiry and manage business correspondence. Depending on context, the legal basis may be Article 6(1)(b) and/or Article 6(1)(f) GDPR.</>],['4. Affiliate and partner links',<>Beauty by Ildy may link to independent brands and merchants, including Nu Skin, Neumi and other beauty, beauty-tech or wellness partners. Once you open a partner site, that provider’s privacy rules apply. Beauty by Ildy does not process payment or checkout on those partner sites.</>],['5. Your rights',<>Subject to applicable conditions, GDPR rights may include access, rectification, erasure, restriction, portability, objection and the right to complain to the competent supervisory authority.</>],['6. Retention and changes',<>Personal data is retained only as long as necessary or legally required. This notice may be updated when website functionality, partners or infrastructure change.</>]]},
 cookies:{title:'Cookie Policy',sections:[['1. Cookies and similar technologies',<>Cookies and local browser storage are technical methods that may be used for preferences, security and site functionality.</>],['2. Current setup',<>The current core version of Beauty by Ildy does not intentionally activate Google Analytics, Google Ads, Meta Pixel or similar advertising trackers. If this changes, this notice and any required consent mechanism will be updated first.</>],['3. Partner websites and outbound links',<>Clicking an affiliate or product link may take you to an independent partner website. That destination may use its own cookies, affiliate parameters and similar tracking technologies under its own policies.</>],['4. Embedded third-party technology',<>If external video, review widgets, partner tools or similar embedded content are added later, non-essential technologies will be activated only with appropriate consent where legally required.</>],['5. Browser controls',<>You can delete or restrict cookies and local site data in your browser settings. Doing so may affect some functionality.</>]]},
 terms:{title:'Terms of Use',sections:[['1. Operator and scope',<>Beauty by Ildy is operated by {business.name}, sole proprietor in Austria. These terms apply to the site’s editorial beauty, beauty-tech, hair, wellness and affiliate content.</>],['2. Not our own webshop',<>Beauty by Ildy does not itself sell or ship partner products unless an offer explicitly says otherwise. A purchase contract on a partner site is concluded directly between the customer and that partner.</>],['3. Price, availability and product data',<>Prices, stock, bundles, shipping territories, promotions, ingredients and product specifications can change. Before purchase, the final partner product page and terms control.</>],['4. Editorial information',<>Beauty by Ildy interprets, compares and curates products and technologies. Content is informational and does not guarantee individual results or replace personalised medical, dermatological, nutritional or other professional advice.</>],['5. Third-party services',<>Beauty by Ildy does not control independent partner websites, stock, delivery or contractual performance. Mandatory legal rights and liabilities remain unaffected.</>],['6. Intellectual property',<>Unauthorised commercial copying, republication or mass automated reuse of original content is prohibited. Third-party trademarks and materials remain owned by their respective rights holders.</>]]},
 affiliate:{title:'Affiliate Disclosure',sections:[['1. Commercial affiliate activity',<>Beauty by Ildy is a commercial beauty, beauty-tech and wellness content platform. Some buttons, recommendations and outbound links may be affiliate, referral or other commercial partner links.</>],['2. How commissions work',<>If a qualifying transaction occurs through an eligible partner link, Beauty by Ildy may receive commission or other agreed remuneration. This normally does not increase the price charged to the customer by the partner.</>],['3. Partner examples',<>Active or planned partner references may include Nu Skin, Neumi, HubisLab, Biodance, Aestura, NIRA, CurrentBody, Medicube, IOPE, Sulwhasoo, Genabelle and others. A brand’s presence does not mean every link is commission-bearing.</>],['4. Editorial independence',<>An affiliate relationship does not guarantee a positive review or ranking. Beauty by Ildy aims to prioritise formulation, technology, safety, evidence and real user value over commission.</>],['5. Gifted and sponsored products',<>If a product or device is supplied free for testing, or content is paid/sponsored, that relationship will be disclosed clearly near the relevant content. Gifting or payment does not guarantee a positive opinion.</>]]},
 health:{title:'Health & Product Disclaimer',sections:[['1. Not medical advice',<>Beauty by Ildy content is informational and editorial. It does not diagnose, treat or cure disease and does not replace personalised advice from a doctor, dermatologist, pharmacist, dietitian or other qualified health professional.</>],['2. Cosmetics and beauty devices',<>Results vary between individuals. Read manufacturer instructions, contraindications and safety warnings before use. Sensitive skin, skin disease, pregnancy, implants, medication or other health conditions may require professional advice before using certain products or devices.</>],['3. Supplements and wellness',<>Food supplements do not replace a varied balanced diet and healthy lifestyle. Wellness content does not claim to prevent, treat or cure disease unless such a claim is legally permitted and properly authorised.</>],['4. Brand claims and evidence',<>We aim to distinguish manufacturer clinical or marketing claims from independent evidence. A small or manufacturer-funded study does not carry the same evidential weight as a large independent clinical trial.</>]]}
 },
 de:{
 imprint:{title:'Impressum',sections:[['Websitebetreiberin und Medieninhaberin',<>Marke / Website: <strong>Beauty by Ildy</strong><br/>Betreiberin: <strong>{business.name}</strong><br/>Rechtsform: Einzelunternehmerin (Österreich)<br/>Geschäftsanschrift: {business.address}<br/>UID: {business.uid}<br/>GISA: {business.gisa}<br/>Eingetragenes Gewerbe: {business.trade}<br/>E-Mail: <a href={`mailto:${business.email}`}>{business.email}</a></>],['Gewerberechtliche Angaben',<>Mitglied der Wirtschaftskammer Burgenland (WKO). Zuständige Behörde: Bezirkshauptmannschaft Jennersdorf, Hauptplatz 15, 8380 Jennersdorf, Österreich. Anwendbares Recht: Gewerbeordnung (GewO).</>],['Offenlegung gemäß § 25 Mediengesetz',<>Medieninhaberin: Beauty by Ildy — {business.name}. Unternehmensgegenstand: Beauty-, Wellness- und Lifestyle-Inhalte sowie Affiliate-Marketing im Rahmen der eingetragenen Tätigkeit. Grundlegende Richtung: unabhängige kuratierte Informationen über Hautpflege, Beauty-Technologie, Haar- und Kopfhautpflege, Wellness und verwandte Produkte. Keine politische oder weltanschauliche Zielsetzung.</>],['Art der Dienstleistung',<>Beauty by Ildy ist eine kommerzielle redaktionelle Affiliate-Marketing-Website. Sie wird nicht als eigener Webshop betrieben: Käufe erfolgen in der Regel auf unabhängigen Partnerseiten; Vertrag, Zahlung, Versand, Rückgabe, Gewährleistung und Kundendienst werden vom jeweiligen Partner geregelt.</>],['Urheberrecht',<>Eigene Texte, Layouts und kreative Inhalte von Beauty by Ildy sind urheberrechtlich geschützt. Namen, Marken, Bilder, Videos und Produktmaterialien Dritter unterliegen den Rechten ihrer jeweiligen Inhaber.</>]]},
 privacy:{title:'Datenschutzerklärung',sections:[['1. Verantwortliche Stelle',<>Verantwortliche: <strong>{business.name}</strong>, Einzelunternehmerin in Österreich. Anschrift: {business.address}. UID: {business.uid}. GISA: {business.gisa}. E-Mail: <a href={`mailto:${business.email}`}>{business.email}</a>.</>],['2. Technische Bereitstellung',<>Für Hosting, Infrastruktur und Codeverwaltung können externe Anbieter eingesetzt werden. Diese können notwendige technische Daten wie IP-Adresse, Browsertyp und Sicherheitsprotokolle nach ihren eigenen Datenschutzregeln verarbeiten.</>],['3. Kontaktanfragen',<>Bei Kontakt per E-Mail verarbeiten wir die übermittelten Daten zur Beantwortung und zur geschäftlichen Kommunikation. Rechtsgrundlage kann je nach Zusammenhang Art. 6 Abs. 1 lit. b und/oder lit. f DSGVO sein.</>],['4. Affiliate- und Partnerlinks',<>Beauty by Ildy kann zu unabhängigen Marken und Händlern verlinken, darunter Nu Skin, Neumi und weitere Beauty-, Beauty-Tech- oder Wellness-Partner. Nach Öffnen der Partnerseite gelten deren Datenschutzregeln. Beauty by Ildy verarbeitet dort weder Checkout noch Zahlung.</>],['5. Betroffenenrechte',<>Unter den gesetzlichen Voraussetzungen bestehen insbesondere Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit, Widerspruch und Beschwerde bei der zuständigen Aufsichtsbehörde.</>],['6. Speicherdauer und Änderungen',<>Daten werden nur so lange gespeichert, wie dies erforderlich oder gesetzlich vorgeschrieben ist. Diese Erklärung kann bei Änderungen von Funktionen, Partnern oder Infrastruktur aktualisiert werden.</>]]},
 cookies:{title:'Cookie-Hinweis',sections:[['1. Cookies und ähnliche Technologien',<>Cookies und lokaler Browserspeicher können für Einstellungen, Sicherheit und Funktionen eingesetzt werden.</>],['2. Aktueller Stand',<>Die aktuelle Basisversion von Beauty by Ildy aktiviert bewusst weder Google Analytics, Google Ads, Meta Pixel noch vergleichbare Werbetracker. Bei Änderungen werden Hinweis und ggf. Einwilligungsmechanismus zuvor aktualisiert.</>],['3. Partnerseiten und externe Links',<>Affiliate- oder Produktlinks können zu unabhängigen Partnerseiten führen. Dort können eigene Cookies, Affiliate-Parameter und ähnliche Trackingtechnologien nach den Regeln des jeweiligen Partners eingesetzt werden.</>],['4. Eingebettete Dritttechnologien',<>Werden später externe Videos, Bewertungswidgets oder Partner-Tools eingebettet, werden nicht notwendige Technologien — soweit rechtlich erforderlich — erst nach geeigneter Einwilligung aktiviert.</>],['5. Browsereinstellungen',<>Cookies und lokale Websitedaten können in den Browsereinstellungen gelöscht oder eingeschränkt werden. Dies kann Funktionen beeinflussen.</>]]},
 terms:{title:'Nutzungsbedingungen',sections:[['1. Betreiberin und Geltungsbereich',<>Beauty by Ildy wird von {business.name}, Einzelunternehmerin in Österreich, betrieben. Diese Bedingungen gelten für redaktionelle Beauty-, Beauty-Tech-, Haar-, Wellness- und Affiliate-Inhalte.</>],['2. Kein eigener Webshop',<>Beauty by Ildy verkauft oder versendet Partnerprodukte nicht selbst, sofern nicht ausdrücklich anders angegeben. Ein Kaufvertrag auf einer Partnerseite kommt direkt zwischen Kundin/Kunde und dem jeweiligen Partner zustande.</>],['3. Preise, Verfügbarkeit und Produktdaten',<>Preise, Lagerbestand, Bundles, Liefergebiete, Aktionen, Inhaltsstoffe und Produktspezifikationen können sich ändern. Vor dem Kauf sind die endgültige Partnerproduktseite und deren Bedingungen maßgeblich.</>],['4. Redaktionelle Informationen',<>Beauty by Ildy interpretiert, vergleicht und kuratiert Produkte und Technologien. Inhalte sind informativ, garantieren keine individuellen Ergebnisse und ersetzen keine persönliche medizinische, dermatologische, ernährungsbezogene oder sonstige Fachberatung.</>],['5. Drittanbieter',<>Beauty by Ildy kontrolliert unabhängige Partnerwebsites, Lagerbestand, Versand oder Vertragserfüllung nicht. Zwingende gesetzliche Rechte bleiben unberührt.</>],['6. Geistiges Eigentum',<>Unbefugtes kommerzielles Kopieren, Wiederveröffentlichen oder automatisiertes massenhaftes Verwenden eigener Inhalte ist untersagt. Marken und Materialien Dritter bleiben Eigentum ihrer Rechteinhaber.</>]]},
 affiliate:{title:'Affiliate-Offenlegung',sections:[['1. Kommerzielle Affiliate-Tätigkeit',<>Beauty by Ildy ist eine kommerzielle Plattform für Beauty-, Beauty-Tech- und Wellness-Inhalte. Einige Schaltflächen, Empfehlungen und externe Links können Affiliate-, Referral- oder sonstige kommerzielle Partnerlinks sein.</>],['2. Provisionen',<>Bei einer qualifizierenden Transaktion über einen entsprechenden Partnerlink kann Beauty by Ildy eine Provision oder andere vereinbarte Vergütung erhalten. Der vom Partner berechnete Preis erhöht sich dadurch in der Regel nicht.</>],['3. Partnerbeispiele',<>Aktive oder geplante Partner können Nu Skin, Neumi, HubisLab, Biodance, Aestura, NIRA, CurrentBody, Medicube, IOPE, Sulwhasoo, Genabelle und weitere Anbieter umfassen. Die Nennung einer Marke bedeutet nicht, dass jeder Link provisionspflichtig ist.</>],['4. Redaktionelle Unabhängigkeit',<>Eine Affiliate-Beziehung garantiert keine positive Bewertung oder Platzierung. Beauty by Ildy priorisiert Formulierung, Technologie, Sicherheit, Evidenz und tatsächlichen Nutzen vor der Provision.</>],['5. Geschenk- und Sponsoringprodukte',<>Kostenlos zur Verfügung gestellte Testprodukte oder bezahlte Kooperationen werden beim betreffenden Inhalt klar gekennzeichnet. Geschenk oder Vergütung garantieren keine positive Meinung.</>]]},
 health:{title:'Gesundheits- & Produkthinweis',sections:[['1. Keine medizinische Beratung',<>Beauty by Ildy bietet redaktionelle Informationen. Die Inhalte diagnostizieren, behandeln oder heilen keine Krankheiten und ersetzen keine individuelle Beratung durch Arzt, Dermatologin, Apotheker, Ernährungsfachkraft oder andere qualifizierte Fachpersonen.</>],['2. Kosmetik und Beauty-Geräte',<>Ergebnisse können individuell unterschiedlich sein. Vor der Anwendung sind Herstellerhinweise, Kontraindikationen und Sicherheitswarnungen zu beachten. Bei empfindlicher Haut, Hauterkrankungen, Schwangerschaft, Implantaten, Medikamenten oder anderen gesundheitlichen Umständen kann fachlicher Rat erforderlich sein.</>],['3. Nahrungsergänzung und Wellness',<>Nahrungsergänzungsmittel ersetzen keine abwechslungsreiche ausgewogene Ernährung und gesunde Lebensweise. Wellness-Inhalte beanspruchen keine Krankheitsprävention, -behandlung oder -heilung, sofern eine solche Aussage nicht rechtlich zulässig und ordnungsgemäß autorisiert ist.</>],['4. Markenclaims und Evidenz',<>Herstellerfinanzierte klinische oder Marketingclaims sollen von unabhängiger Evidenz unterschieden werden. Kleine oder vom Hersteller finanzierte Studien haben nicht dieselbe Aussagekraft wie große unabhängige klinische Studien.</>]]}
 }
};

export function LegalPage({lang='hu',type='imprint'}){const d=(docs[lang]||docs.hu)[type]||docs.hu.imprint;const l=legalLabels[lang]||legalLabels.hu;return <main className="legalPage"><a className="legalBack" href="#top">← {l.back}</a><p className="eyebrow">BEAUTY BY ILDY · LEGAL</p><h1>{d.title}</h1><p className="legalUpdated">{l.updated}</p><div className="legalSections">{d.sections.map(([title,body])=><section key={title}><h2>{title}</h2><div>{body}</div></section>)}</div></main>}
