import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight,Menu,X,ShieldCheck,Microscope,HeartPulse} from 'lucide-react';
import {LegalPage,legalLabels} from './legal.jsx';
import './styles.css';

const copy={
 hu:{nav:[['SZÉPSÉG','beauty'],['BEAUTY TECH','tech'],['WELLNESS','wellness'],['HAJ & FEJBŐR','hair'],['MEGOLDÁSOK','solutions'],['MÁRKÁK','brands'],['MAGAZIN','magazine']],eyebrow:'BEAUTY • TECHNOLOGY • WELLNESS',title:'A szépség új dimenziója.',sub:'Bőrápolás, innovatív technológia és wellness – kívül-belül.',cta:'Fedezd fel a válogatást',choose:'MIT SZERETNÉL TÁMOGATNI?',needs:['Ráncok & feszesség','Hidratálás','Barrier & érzékenység','Pigmentáció','Pórusok','Problémás bőr','Haj & fejbőr','Energia & vitalitás'],pillars:[['BEAUTY','Tudatos bőrápolás','Hatóanyagok, formulák és rutinok valódi igények szerint.'],['BEAUTY TECH','Technológia otthon','LED, lézer, mikroáram és más korszerű beauty eszközök.'],['WELLNESS','Szépség belülről','Energia, vitalitás és mindennapi jóllét gondosan válogatva.']],hairTitle:'Haj & fejbőr',hairText:'Célzott haj- és fejbőrápolás, gondosan válogatott formulákkal és technológiákkal.',routines:'VÁLOGATOTT RUTINOK',routineSub:'Nem egyetlen márkához kötünk. Olyan összeállításokat készítünk, ahol az egyes lépések együtt adnak értelmes rutint.',routineCards:[['GLOW ROUTINE','Fény, hidratáltság, egységesebb bőrérzet.'],['AGE-WELL ROUTINE','Retinoid, peptidek és célzott beauty tech.'],['BARRIER RESET','Kímélő, barrier-központú rutin érzékenyebb időszakokra.'],['ENERGY RESET','Mindennapi vitalitást támogató wellness-válogatás.']],standards:'MI ALAPJÁN VÁLOGATUNK?',standardCards:[['Hatékonyság','Összetétel, hatóanyagok, technológia és elérhető vizsgálatok.'],['Biztonság','INCI, irritációs kockázat, használati korlátok és ésszerű állítások.'],['Valódi érték','Nem attól kerül be valami, hogy van partnerprogramja.']],brands:'VÁLOGATOTT MÁRKÁK',brandSub:'Nem a márkanév dönt. A technológia, a formula és az, hogy mire van valóban szükséged.',magTitle:'MAGAZIN & ÚTMUTATÓK',magCards:[['Retinol vagy retinal?','Mi a különbség, kinek melyik lehet jobb, és hogyan érdemes bevezetni?'],['LED, lézer vagy mikroáram?','Mit tudnak valójában az otthoni beauty eszközök — és mit nem?'],['PDRN: trend vagy érték?','Mit jelent a PDRN a kozmetikumokban, és milyen bizonyítékokat érdemes keresni?']],footer:'Beauty & wellness, carefully curated.',disclaimer:'Egyes linkek partnerlinkek lehetnek. A vásárlás a partner weboldalán történik; a válogatás ettől független.'},
 en:{nav:[['BEAUTY','beauty'],['BEAUTY TECH','tech'],['WELLNESS','wellness'],['HAIR & SCALP','hair'],['SOLUTIONS','solutions'],['BRANDS','brands'],['MAGAZINE','magazine']],eyebrow:'BEAUTY • TECHNOLOGY • WELLNESS',title:'A new dimension of beauty.',sub:'Skincare, innovative technology and wellness – inside and out.',cta:'Explore the edit',choose:'WHAT WOULD YOU LIKE TO SUPPORT?',needs:['Wrinkles & firmness','Hydration','Barrier & sensitivity','Pigmentation','Pores','Blemish-prone skin','Hair & scalp','Energy & vitality'],pillars:[['BEAUTY','Intentional skincare','Actives, formulas and routines selected around real needs.'],['BEAUTY TECH','Technology at home','LED, laser, microcurrent and modern beauty devices.'],['WELLNESS','Beauty from within','Energy, vitality and everyday wellbeing, carefully selected.']],hairTitle:'Hair & scalp',hairText:'Targeted hair and scalp care with carefully selected formulas and technologies.',routines:'CURATED ROUTINES',routineSub:'We are not tied to one brand. Each edit combines steps that make sense together.',routineCards:[['GLOW ROUTINE','Radiance, hydration and a more even-looking complexion.'],['AGE-WELL ROUTINE','Retinoids, peptides and targeted beauty tech.'],['BARRIER RESET','A gentle barrier-focused routine for sensitive periods.'],['ENERGY RESET','A wellness edit for everyday vitality.']],standards:'HOW WE CURATE',standardCards:[['Efficacy','Formulation, actives, technology and available evidence.'],['Safety','INCI, irritation potential, use limitations and responsible claims.'],['Real value','A product is not selected simply because it has an affiliate program.']],brands:'CURATED BRANDS',brandSub:'Brand name comes second. Technology, formulation and your real needs come first.',magTitle:'MAGAZINE & GUIDES',magCards:[['Retinol or retinal?','What is the difference, who may prefer which, and how to introduce them?'],['LED, laser or microcurrent?','What at-home beauty devices can realistically do — and what they cannot.'],['PDRN: trend or value?','What PDRN means in skincare and what kind of evidence is worth looking for.']],footer:'Beauty & wellness, carefully curated.',disclaimer:'Some links may be affiliate links. Purchases take place on partner websites; curation remains independent.'},
 de:{nav:[['BEAUTY','beauty'],['BEAUTY TECH','tech'],['WELLNESS','wellness'],['HAAR & KOPFHAUT','hair'],['LÖSUNGEN','solutions'],['MARKEN','brands'],['MAGAZIN','magazine']],eyebrow:'BEAUTY • TECHNOLOGIE • WELLNESS',title:'Eine neue Dimension der Schönheit.',sub:'Hautpflege, innovative Technologie und Wellness – von innen und außen.',cta:'Auswahl entdecken',choose:'WAS MÖCHTEST DU UNTERSTÜTZEN?',needs:['Falten & Festigkeit','Feuchtigkeit','Barriere & Sensibilität','Pigmentierung','Poren','Unreine Haut','Haar & Kopfhaut','Energie & Vitalität'],pillars:[['BEAUTY','Bewusste Hautpflege','Wirkstoffe, Formulierungen und Routinen nach echten Bedürfnissen.'],['BEAUTY TECH','Technologie für zu Hause','LED, Laser, Mikrostrom und moderne Beauty-Geräte.'],['WELLNESS','Schönheit von innen','Energie, Vitalität und tägliches Wohlbefinden, sorgfältig ausgewählt.']],hairTitle:'Haar & Kopfhaut',hairText:'Gezielte Haar- und Kopfhautpflege mit sorgfältig ausgewählten Formulierungen und Technologien.',routines:'KURATIERTE ROUTINEN',routineSub:'Wir sind nicht an eine einzelne Marke gebunden. Jeder Edit kombiniert Schritte, die sinnvoll zusammenpassen.',routineCards:[['GLOW ROUTINE','Ausstrahlung, Feuchtigkeit und ein ebenmäßigeres Hautbild.'],['AGE-WELL ROUTINE','Retinoide, Peptide und gezielte Beauty-Technologie.'],['BARRIER RESET','Sanfte, barrierestärkende Routine für sensible Phasen.'],['ENERGY RESET','Wellness-Auswahl für tägliche Vitalität.']],standards:'WIE WIR AUSWÄHLEN',standardCards:[['Wirksamkeit','Formulierung, Wirkstoffe, Technologie und verfügbare Evidenz.'],['Sicherheit','INCI, Reizpotenzial, Anwendungsgrenzen und verantwortungsvolle Aussagen.'],['Echter Wert','Ein Produkt wird nicht nur wegen eines Partnerprogramms ausgewählt.']],brands:'KURATIERTE MARKEN',brandSub:'Nicht der Markenname entscheidet. Technologie, Formulierung und dein tatsächlicher Bedarf stehen zuerst.',magTitle:'MAGAZIN & GUIDES',magCards:[['Retinol oder Retinal?','Unterschiede, Einsatzbereiche und ein sinnvoller Einstieg.'],['LED, Laser oder Mikrostrom?','Was Beauty-Geräte für zu Hause realistisch leisten können — und was nicht.'],['PDRN: Trend oder Mehrwert?','Was PDRN in Kosmetik bedeutet und welche Evidenz wirklich relevant ist.']],footer:'Beauty & wellness, carefully curated.',disclaimer:'Einige Links können Partnerlinks sein. Der Kauf erfolgt auf Partnerseiten; die Auswahl bleibt unabhängig.'}
};
const brands=[['Nu Skin','AVAILABLE NOW','Beauty tech + skincare + wellness'],['Neumi','AVAILABLE NOW','Delivery technology + wellness'],['HubisLab','CURATED','Professional K-beauty'],['Biodance','CURATED','K-beauty + PDRN'],['Aestura','CURATED','Barrier care'],['NIRA','CURATED','At-home laser'],['CurrentBody','CURATED','LED + beauty tech'],['Medicube','CURATED','K-beauty + devices'],['IOPE','CURATED','Korean R&D skincare'],['Sulwhasoo','CURATED','Premium Korean skincare'],['Genabelle','CURATED','Clinic-born PDRN skincare']];
const needTargets=['routines','routines','routines','routines','routines','routines','hair','wellness'];
const legalTypes=['imprint','privacy','cookies','terms','affiliate','health'];
function currentLegal(){const h=window.location.hash.replace('#','');return h.startsWith('legal-')?h.slice(6):null}
function App(){const [lang,setLang]=useState('hu');const [open,setOpen]=useState(false);const [legal,setLegal]=useState(currentLegal());const t=copy[lang];const labels=legalLabels[lang];useEffect(()=>{const fn=()=>{setLegal(currentLegal());window.scrollTo(0,0)};window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);return <div>
<header><a className="logo" href="#top">BEAUTY <span>BY ILDY</span><small>Beauty & wellness, carefully curated.</small></a>{!legal&&<nav>{t.nav.map(([n,id])=><a href={`#${id}`} key={id}>{n}</a>)}</nav>}<div className="actions"><div className="langs">{['hu','en','de'].map(l=><button className={lang===l?'active':''} onClick={()=>setLang(l)} key={l}>{l.toUpperCase()}</button>)}</div>{!legal&&<button className="mobile" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>}</div></header>
{open&&!legal&&<div className="mobileNav">{t.nav.map(([n,id])=><a onClick={()=>setOpen(false)} href={`#${id}`} key={id}>{n}</a>)}</div>}
{legal?<LegalPage lang={lang} type={legal}/>:<main id="top">
<section className="hero"><div className="glow"></div><div className="heroContent"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1><p className="lead">{t.sub}</p><a className="primary" href="#solutions">{t.cta}<ArrowRight size={17}/></a></div></section>
<section id="solutions" className="needs"><p>{t.choose}</p><div>{t.needs.map((n,i)=><a className="needLink" href={`#${needTargets[i]}`} key={n}>{n}</a>)}</div></section>
<section className="pillars"><article id="beauty"><span>01</span><p className="label">{t.pillars[0][0]}</p><h2>{t.pillars[0][1]}</h2><p>{t.pillars[0][2]}</p><a href="#routines">DISCOVER <ArrowRight size={15}/></a></article><article id="tech"><span>02</span><p className="label">{t.pillars[1][0]}</p><h2>{t.pillars[1][1]}</h2><p>{t.pillars[1][2]}</p><a href="#brands">DISCOVER <ArrowRight size={15}/></a></article><article id="wellness"><span>03</span><p className="label">{t.pillars[2][0]}</p><h2>{t.pillars[2][1]}</h2><p>{t.pillars[2][2]}</p><a href="#routines">DISCOVER <ArrowRight size={15}/></a></article></section>
<section id="hair" className="featureBand"><div><h2>{t.hairTitle}</h2><p>{t.hairText}</p></div><div className="featureMark">H&S</div></section>
<section id="routines" className="routines"><h2>{t.routines}</h2><p className="sectionIntro">{t.routineSub}</p><div className="routineGrid">{t.routineCards.map((r,i)=><article key={r[0]}><small>0{i+1}</small><h3>{r[0]}</h3><p>{r[1]}</p><a href="#brands">EXPLORE <ArrowRight size={14}/></a></article>)}</div></section>
<section className="standards"><div className="standardsHead"><h2>{t.standards}</h2></div><div className="standardGrid">{t.standardCards.map((s,i)=>{const Icon=[Microscope,ShieldCheck,HeartPulse][i];return <article key={s[0]}><Icon size={24}/><h3>{s[0]}</h3><p>{s[1]}</p></article>})}</div></section>
<section id="brands" className="brands"><h2>{t.brands}</h2><p className="brandIntro">{t.brandSub}</p><div className="brandGrid">{brands.map(([b,status,desc])=><div key={b}><span>{b}</span><small>{status}</small><em>{desc}</em></div>)}</div></section>
<section id="magazine" className="magazine"><p className="eyebrow">EDITORIAL</p><h2>{t.magTitle}</h2><div className="magGrid">{t.magCards.map((m,i)=><article key={m[0]}><span>0{i+1}</span><h3>{m[0]}</h3><p>{m[1]}</p><a href="#">READ GUIDE <ArrowRight size={14}/></a></article>)}</div></section>
</main>}
<footer><div><div className="logo inverse">BEAUTY <span>BY ILDY</span><small>{t.footer}</small></div><p className="fineprint">{t.disclaimer}</p><div className="legalLinks">{legalTypes.map(type=><a key={type} href={`#legal-${type}`}>{labels[type]}</a>)}</div></div><p>HU · EN · DE</p></footer>
</div>}
createRoot(document.getElementById('root')).render(<App/>);