import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, Menu, X, Sparkles} from 'lucide-react';
import './styles.css';

const copy={
 hu:{nav:['SZÉPSÉG','BEAUTY TECH','WELLNESS','HAJ & FEJBŐR','MEGOLDÁSOK','MÁRKÁK','MAGAZIN'],eyebrow:'BEAUTY • TECHNOLOGY • WELLNESS',title:'Szépség és jóllét, gondosan válogatva.',sub:'Hatékony bőrápolás, innovatív otthoni beauty technológia és wellness — függetlenül válogatva, egy helyen.',cta:'Fedezd fel a válogatást',choose:'MIT SZERETNÉL TÁMOGATNI?',pillars:[['BEAUTY','Tudatos bőrápolás','Hatóanyagok, formulák és rutinok valódi igények szerint.'],['BEAUTY TECH','Technológia otthon','LED, lézer, mikroáram és más korszerű beauty eszközök.'],['WELLNESS','Szépség belülről','Energia, vitalitás és mindennapi jóllét gondosan válogatva.']],brands:'VÁLOGATOTT MÁRKÁK',brandSub:'Nem a márkanév dönt. A technológia, a formula és az, hogy mire van valóban szükséged.',footer:'Beauty & wellness, carefully curated.'},
 en:{nav:['BEAUTY','BEAUTY TECH','WELLNESS','HAIR & SCALP','SOLUTIONS','BRANDS','MAGAZINE'],eyebrow:'BEAUTY • TECHNOLOGY • WELLNESS',title:'Beauty & wellness, carefully curated.',sub:'Effective skincare, innovative at-home beauty technology and wellness — independently selected in one place.',cta:'Explore the edit',choose:'WHAT WOULD YOU LIKE TO SUPPORT?',pillars:[['BEAUTY','Intentional skincare','Actives, formulas and routines selected around real needs.'],['BEAUTY TECH','Technology at home','LED, laser, microcurrent and modern beauty devices.'],['WELLNESS','Beauty from within','Energy, vitality and everyday wellbeing, carefully selected.']],brands:'CURATED BRANDS',brandSub:'Brand name comes second. Technology, formulation and your real needs come first.',footer:'Beauty & wellness, carefully curated.'},
 de:{nav:['BEAUTY','BEAUTY TECH','WELLNESS','HAAR & KOPFHAUT','LÖSUNGEN','MARKEN','MAGAZIN'],eyebrow:'BEAUTY • TECHNOLOGIE • WELLNESS',title:'Beauty & Wellness, sorgfältig kuratiert.',sub:'Wirksame Hautpflege, innovative Beauty-Technologie für zu Hause und Wellness — unabhängig ausgewählt an einem Ort.',cta:'Auswahl entdecken',choose:'WAS MÖCHTEST DU UNTERSTÜTZEN?',pillars:[['BEAUTY','Bewusste Hautpflege','Wirkstoffe, Formulierungen und Routinen nach echten Bedürfnissen.'],['BEAUTY TECH','Technologie für zu Hause','LED, Laser, Mikrostrom und moderne Beauty-Geräte.'],['WELLNESS','Schönheit von innen','Energie, Vitalität und tägliches Wohlbefinden, sorgfältig ausgewählt.']],brands:'KURATIERTE MARKEN',brandSub:'Nicht der Markenname entscheidet. Technologie, Formulierung und dein tatsächlicher Bedarf stehen zuerst.',footer:'Beauty & wellness, carefully curated.'}
};
const brands=['Nu Skin','Neumi','HubisLab','Biodance','Aestura','NIRA','CurrentBody','Medicube','IOPE','Sulwhasoo','Genabelle'];
const needs=['Ráncok & feszesség','Hidratálás','Barrier & érzékenység','Pigmentáció','Pórusok','Problémás bőr','Haj & fejbőr','Energia & vitalitás'];
function App(){const [lang,setLang]=useState('hu');const [open,setOpen]=useState(false);const t=copy[lang];return <div>
<header><a className="logo" href="#">BEAUTY <span>BY ILDY</span><small>Beauty & wellness, carefully curated.</small></a><nav>{t.nav.map(n=><a href="#" key={n}>{n}</a>)}</nav><div className="actions"><div className="langs">{['hu','en','de'].map(l=><button className={lang===l?'active':''} onClick={()=>setLang(l)} key={l}>{l.toUpperCase()}</button>)}</div><button className="mobile" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>
{open&&<div className="mobileNav">{t.nav.map(n=><a href="#" key={n}>{n}</a>)}</div>}
<main>
<section className="hero"><div className="glow"></div><div className="heroContent"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1><p className="lead">{t.sub}</p><a className="primary" href="#pillars">{t.cta}<ArrowRight size={17}/></a></div><div className="orb"><div className="orbInner"><Sparkles size={28}/><span>CURATED<br/>BY ILDY</span></div></div></section>
<section className="needs"><p>{t.choose}</p><div>{needs.map(n=><button key={n}>{n}</button>)}</div></section>
<section id="pillars" className="pillars">{t.pillars.map((p,i)=><article key={p[0]}><span>0{i+1}</span><p className="label">{p[0]}</p><h2>{p[1]}</h2><p>{p[2]}</p><a href="#">DISCOVER <ArrowRight size={15}/></a></article>)}</section>
<section className="brands"><p className="eyebrow">BEAUTY BY ILDY EDIT</p><h2>{t.brands}</h2><p className="brandIntro">{t.brandSub}</p><div className="brandGrid">{brands.map((b,i)=><div key={b}><span>{b}</span><small>{i<2?'AVAILABLE NOW':'CURATED'}</small></div>)}</div></section>
</main><footer><div className="logo inverse">BEAUTY <span>BY ILDY</span><small>{t.footer}</small></div><p>HU · EN · DE</p></footer>
</div>}
createRoot(document.getElementById('root')).render(<App/>);