import React,{useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,CheckCircle2,FlaskConical,Info,Layers3,Search} from 'lucide-react';
import './products.css';

const P=(slug,brand,name,category,ingredients,badge,forWhom,why,watch)=>({slug,brand,name,category,ingredients,badge,forWhom,why,watch});

export const products=[
P('hubislab-eternal','HUBISLAB','Premium Active Eternal Eye & Face Cream','agewell',['BOTALIX™ / Acmella','peptidek','squalane','panthenol','Centella asiatica'],'tested','Finom vonalakra, szemkörnyékre és komfortosabb, teltebb bőrérzetre keresett prémium rutinba.','Összetett formula, többféle hidratáló, nyugtató és age-well komponenssel; személyes használati tapasztalat is kapcsolódik hozzá.','A BOTALIX™-hoz kapcsolódó „botox-hatású” marketinget nem kezeljük azonosként az injekciós botulinum-toxinnal; a teljes INCI és a késztermék-adat számít.'),
P('medicube-pdrn','MEDICUBE','PDRN Pink Hyaluronic Moisturizing Cream','pdrn',['Sodium DNA / PDRN','niacinamide','ceramidok','panthenol','hialuronsav-komplex'],'selected','Hidratáló-regeneráló rutinba, különösen akkor, ha PDRN mellett barrier-támogatás is cél.','Jó példa arra, hogyan kell egy trendi PDRN-terméket a teljes formulán keresztül értékelni, nem csak egyetlen hero összetevő alapján.','A Sodium DNA/PDRN koncentrációját csak hivatalosan igazolt adat alapján írjuk ki; eltérő piaci formulák előfordulhatnak.'),
P('iope-xmd-stem-iii','IOPE','XMD Stem III Clinical Recovery Serum','pdrn',['PDRN / DNA-komplex','hialuronsav','Centella-komponensek','peptid'],'new','Prémium regeneráló szérumot keresőknek, akiknél a hidratálás és az age-well fókusz együtt fontos.','Érdekes R&D-központú koncepció, többféle delivery- és hidratáló komponenssel.','A gyártói klinikai kommunikációt elkülönítjük a független szakirodalomtól.'),
P('iope-retinol-rx-2','IOPE','Retinol RX 2% Reti-jection Serum','agewell',['retinoid-komplex','retinol','spicule delivery'],'new','Tapasztaltabb retinoid-használóknak, fokozatos bevezetéssel.','Retinoid és spicule delivery egy formulában: jó Beauty Tech–skincare átmenet.','A „2%” megnevezést nem értelmezzük automatikusan 2% tiszta retinolként; az irritációs kockázat miatt lassú bevezetés szükséges.'),
P('aestura-atobarrier365-cream','AESTURA','Atobarrier365 Cream','barrier',['Ceramide NP','cholesterol','squalane','phytosphingosine'],'selected','Száraz, érzékenyebb vagy sérült barrierű bőrre, különösen egyszerűbb rutinban.','Klasszikus barrier-lipid logikára épülő formula, ceramiddal, koleszterinnel és szkvalánnal.','A jó barrier-formula sem univerzális; egyéni tolerancia és teljes INCI ellenőrzés szükséges.'),
P('aestura-hydro-soothing-cream','AESTURA','Atobarrier365 Hydro Soothing Cream','barrier',['ceramidok','hialuronsav','niacinamide','nyugtató hidratálók'],'new','Vízhiányos, érzékenyebb, de könnyebb textúrát kedvelő bőrre.','A barrier-vonal könnyebb, hidratálóbb alternatívája.','A formula aktuális verzióját és regionális INCI-jét külön ellenőrizzük.'),
P('aestura-cera-ha-serum','AESTURA','Atobarrier365 Hydro Cera-HA Serum','barrier',['ceramidok','hialuronsav-komplex','humektánsok'],'selected','Rétegezhető hidratáló-barrier szérumot keresőknek.','Ceramid + hialuronsav kombinációval könnyen beilleszthető többféle rutinba.','A hidratálás mértékét nem az összetevők száma, hanem a teljes formula határozza meg.'),
P('biodance-caviar-pdrn-capsule-cream','BIODANCE','Rejuvenating Caviar PDRN Capsule Cream','pdrn',['PDRN-vonal','hidratálók','emolliensek'],'new','Gazdagabb regeneráló krémet keresőknek, PDRN fókuszú rutinban.','Érdekes kapszulás textúra és PDRN-koncepció.','A „caviar PDRN” marketingmegnevezést nem tekintjük automatikusan magasabb biológiai hatás bizonyítékának.'),
P('biodance-caviar-pdrn-bubble-booster','BIODANCE','Caviar PDRN Liposome Bubble Booster','pdrn',['PDRN-vonal','liposzómás delivery','hidratálók'],'new','Könnyebb booster-lépést keresőknek PDRN-rutinban.','Delivery-koncepciója miatt érdekes, különösen edukációs szempontból.','A liposzóma önmagában nem bizonyít nagyobb bőrbejutást; késztermék-adat szükséges.'),
P('biodance-caviar-pdrn-toner-pad','BIODANCE','Caviar PDRN Dual Gel Toner Pad','pdrn',['PDRN-vonal','hidratáló gélrendszer'],'new','Gyors, kényelmes hidratáló tonerpados lépést keresőknek.','Jól mutatja, hogyan kerül a PDRN különböző formátumokba.','A tonerpados forma dörzsölése érzékeny bőrön irritáló lehet.'),
P('biodance-caviar-pdrn-eye-patch','BIODANCE','Caviar PDRN Eye Patch','eye',['PDRN-vonal','hidratálók'],'new','Átmeneti hidratáló, komfortfokozó szemkörnyékápolásra.','Kiegészítő, élményközpontú termék PDRN-vonalban.','A szempatch látványos rövid távú hidratálása nem azonos tartós ránccsökkentéssel.'),
P('sulwhasoo-ginseng-cream','SULWHASOO','Concentrated Ginseng Rejuvenating Cream','agewell',['ginseng / ginszenozidok','peptidek','antioxidánsok','emolliensek'],'premium','Luxus age-well rutint keresőknek, gazdagabb textúrával.','Erős márka-R&D háttér és komplex, prémium formula.','A ginsenggel kapcsolatos kutatásokat különválasztjuk a késztermék gyártói vizsgálataitól.'),
P('sulwhasoo-ginseng-serum','SULWHASOO','Concentrated Ginseng Rejuvenating Serum','agewell',['ginseng / ginszenozidok','antioxidánsok','hidratálók'],'premium','Könnyebb prémium age-well szérumot keresőknek.','A ginseng-vonal koncentráltabb, szérumos alternatívája.','A prémium ár nem önmagában a hatékonyság bizonyítéka.'),
P('genabelle-pdrn-cream','GENABELLE','PDRN Rejuvenating Cream','pdrn',['PDRN / Sodium DNA','hidratálók','barrier-támogatók'],'selected','PDRN mellett krémes barrier-támogatást keresőknek.','Egyszerűen értelmezhető PDRN + hidratálás irány.','A pontos Sodium DNA mennyiséget és a teljes formulát ellenőrzött forrásból kell rögzíteni.'),
P('genabelle-pdrn-serum','GENABELLE','PDRN Rejuvenating Serum','pdrn',['PDRN / Sodium DNA','humektánsok','nyugtató összetevők'],'selected','Könnyebb PDRN-szérumot keresőknek.','Jól párosítható más barrier- vagy hidratáló lépésekkel.','PDRN-termékek között jelentős lehet a formula- és koncentrációkülönbség.'),
P('axis-y-triple-pdrn','AXIS-Y','Triple PDRN Barrier Boost Serum','pdrn',['Sodium DNA / növényi PDRN-koncepció','panthenol','NAD+','sh-Oligopeptide-1'],'new','Trendérzékeny, de barrier-fókuszú szérumot keresőknek.','PDRN, NAD+ és peptid egy termékben — jó példa a 2026-os többfunkciós trendekre.','A növényi PDRN és NAD+ kozmetikai állításait korai/ígéretes területként kezeljük, nem kész tényként.'),
P('axis-y-panthenol-10','AXIS-Y','Panthenol 10 Skin Smoothing Shield Cream','barrier',['panthenol','barrier-támogató lipidek','nyugtató összetevők'],'selected','Érzékenyebb, húzódó vagy barrier-terhelt bőrre.','Magas panthenol-fókusz és egyszerűen érthető barrier-pozicionálás.','A 10% panthenol mellett is a teljes formula és az egyéni tolerancia döntő.'),
P('axis-y-dark-spot','AXIS-Y','Dark Spot Correcting Glow Serum','pigment',['niacinamide','növényi kivonatok','hidratálók'],'selected','Egyenetlen tónus és pigmentfoltok rutinszintű támogatására.','Niacinamidos, könnyen rétegezhető pigmentációs opció.','Fényvédelem nélkül a pigmentációs rutin eredménye korlátozott; irritáció esetén egyszerűsíteni kell.'),
P('skin1004-centella-ampoule','SKIN1004','Madagascar Centella Ampoule','soothe',['Centella asiatica kivonat'],'selected','Minimalistább, nyugtató formulát keresőknek.','Jó példa arra, hogy nem minden hatékony rutin igényel sok összetevőt.','Centella sem garantál irritációmentességet mindenkinél; patch teszt indokolt lehet.'),
P('skin1004-probio-cica','SKIN1004','Probio-Cica Intensive Ampoule','barrier',['fermentált Centella-komplex','ceramid/barrier fókusz','humektánsok'],'selected','Érzékenyebb, barrier-támogatást igénylő bőrre, gazdagabb szérumos lépésként.','Centella + barrier logika egy komplexebb formulában.','Fermentált összetevők sem jelentenek automatikusan jobb tolerálhatóságot.'),
P('anua-pdrn-ha-serum','ANUA','PDRN Hyaluronic Acid Capsule 100 Serum','pdrn',['PDRN-vonal','hialuronsav-komplex','hidratálók'],'selected','Hidratálásközpontú PDRN-szérumot keresőknek.','PDRN és többféle hidratáló rendszer kombinációja.','A „100” terméknév nem kezelhető koncentrációként; csak hivatalos százalékadatot közlünk.'),
P('haruharu-rose-pdrn','HARUHARU WONDER','Rose PDRN Firming Serum','pdrn',['PDRN-koncepció','rose complex','hidratálók'],'selected','Könnyebb, feszességre pozicionált PDRN-szérumot keresőknek.','Érdekes növényi/alternatív PDRN-koncepció.','A növényi eredetű DNS-fragmentumok klinikai egyenértékűsége nem feltételezhető.'),
P('haruharu-nad-mist','HARUHARU WONDER','Black Rice Probiotics Barrier 2% NAD+ Serum Mist','barrier',['NAD+','black rice','probiotikus/fermentált összetevők','hidratálók'],'trend','Kényelmes barrier-mistet és új hatóanyagkoncepciót keresőknek.','NAD+ miatt edukációs szempontból különösen érdekes.','A topikális NAD+ kozmetikai bizonyítéka korai; nem kommunikáljuk „sejtfiatalítóként”.'),
P('medipeel-phyto-ex-pdrn-eye','MEDI-PEEL','Phyto Ex PDRN Eye Cream','eye',['PDRN-koncepció','peptidek','exoszóma-marketinggel társított összetevők'],'selected','Komplex szemkörnyékápolót keresőknek peptidekkel és PDRN-koncepcióval.','Jó kritikai elemzési példa a PDRN + exoszóma trend miatt.','Az „exoszóma” szó különösen szigorú ellenőrzést igényel; kozmetikai kivonatok és valódi, karakterizált exoszómák nem azonosak.'),
P('thesaem-aloe-99','THE SAEM','Jeju Fresh Aloe 99% Soothing Gel','soothe',['Aloe barbadensis leaf extract','glycerin','növényi kivonatok'],'tested','Egyszerű, multifunkcionális nyugtató-hidratáló gélként arcra vagy testre.','Jó ár-értékű, személyesen is kipróbált, könnyen érthető termék.','Illatanyag vagy egyéb potenciális irritáns miatt érzékeny bőrön érdemes óvatosan tesztelni.'),
P('nature-republic-argan-hair','NATURE REPUBLIC','Argan Essential Deep Care Hair Essence','hair',['argánolaj','szilikonos hajsimító rendszer','emolliensek'],'tested','Száraz, fénytelen hajhosszra és hajvégekre.','Személyesen bevált, gyors kozmetikai javulást adó hajesszencia.','A hajszál felszíni simítása és fényesítése nem azonos a hajhagymák vagy hajhullás kezelésével.'),
P('floland-eyelash-serum','FLOLAND','Nutrition Eyelash Serum','eye',['peptidek','protein-komplex','kondicionáló összetevők'],'tested','Törékenyebb, szárazabb szempillák kondicionálására.','Személyesen ajánlott termék, peptid/protein fókuszú formulával.','A kozmetikai dúsabb megjelenés nem azonos gyógyszeres szempillanövesztő hatással.'),
P('labo-h-scalp-strengthening','LABO-H','Scalp Strengthening Hair Loss Care Shampoo','hair',['fejbőr-fókuszú tisztító rendszer','kondicionálók','növényi összetevők'],'selected','Fejbőr-fókuszú hajápolási rutinhoz.','Jó belépő a Beauty by Ildy haj- és fejbőrápolási szekciójába.','Samponnál különválasztjuk a fejbőr komfortját a valódi hajhullás-kezelési bizonyítéktól.'),
P('mise-en-scene-perfect-serum','MISE-EN-SCÈNE','Perfect Serum','hair',['hajsimító olaj/emolliens rendszer','szilikonok','növényi olajok'],'selected','Fényesebb, simább hajhosszhoz, különösen száraz végeken.','Klasszikus koreai hajszérum-kategória, jól érzékelhető kozmetikai hatással.','A szilikonok nem „rossz” összetevők: itt funkcionális hajsimító szerepük van; felhalmozódás egyéni lehet.'),
P('abib-pdrn-retinal-eye-patch','ABIB','PDRN Retinal Eye Patch Glow Jelly','eye',['Sodium DNA','retinal','niacinamide','panthenol','squalane','caffeine'],'new','Tapasztaltabb felhasználóknak, akik retinallos szemkörnyékápolást keresnek.','Retinal + PDRN + koffein kombináció miatt érdekes, többcélú termék.','Retinal a szemkörnyéken irritálhat; gyakoriságot fokozatosan kell kialakítani, és a pontos koncentrációt ellenőrizni kell.')
];

const T={
 hu:{back:'Vissza a főoldalra',title:'VÁLOGATOTT TERMÉKEK',lead:'30 különböző termék, kategóriákba rendezve. Nem egyetlen márkát mutatunk: formulát, használhatóságot és a rendelkezésre álló bizonyítékot nézzük.',all:'MIND',open:'RÉSZLETES ADATLAP',ingredients:'FŐ ÖSSZETEVŐK / FORMULA-FÓKUSZ',detail:'BEAUTY BY ILDY TERMÉKADATLAP',forWhom:'KINEK LEHET ÉRDEKES?',why:'MIÉRT KERÜLT A VÁLOGATÁSBA?',science:'MIT MOND A TUDOMÁNY?',watch:'FONTOS TUDNI',formula:'FORMULA TÉRKÉP',buy:'VÁSÁRLÁS',buyText:'A vásárlási lehetőséget termékenként kapcsoljuk be, amikor a végleges értékesítési csatorna rendelkezésre áll.',inci:'TELJES INCI',inciText:'A teljes, aktuális INCI-t kizárólag ellenőrzött gyártói vagy csomagolási adat alapján tesszük közzé. Koncentrációt nem következtetünk az INCI sorrendjéből.',reviewed:'Szakmai adatlap · folyamatosan frissítve',search:'Keresés termék vagy márka szerint…',count:'termék',categories:{agewell:'AGE-WELL / RÁNC & FESZESSÉG',pdrn:'PDRN & REGENERÁCIÓ',barrier:'BARRIER & HIDRATÁLÁS',pigment:'PIGMENTÁCIÓ',soothe:'NYUGTATÁS & ÉRZÉKENYSÉG',eye:'SZEMKÖRNYÉK & SZEMPILLA',hair:'HAJ & FEJBŐR'},badges:{tested:'SZEMÉLYESEN TESZTELT',selected:'SZAKMAI VÁLOGATÁS',new:'2026 ÚJDONSÁG / AKTUÁLIS',premium:'PRÉMIUM VÁLOGATÁS',trend:'KORAI / TRENDTERÜLET'},scienceText:{agewell:'A retinoidok mögött erős bizonyíték áll; peptideknél és növényi komplexeknél az evidenciaszint változó, ezért a készterméket külön is vizsgáljuk.',pdrn:'A topikális PDRN humán kutatása ígéretes, de nem általánosítható minden PDRN-termékre. Forrás, molekulaméret, koncentráció, delivery és késztermék-adat számít.',barrier:'Ceramidok, koleszterin, humektánsok és nyugtató összetevők szerepe jól ismert; a teljes formula és a tolerálhatóság döntő.',pigment:'A pigmentációs rutinban az aktív összetevő mellett a következetes fényvédelem alapvető.',soothe:'Nyugtató növényi kivonatok és hidratálók segíthetnek, de érzékeny bőrnél az irritánsokat külön ellenőrizzük.',eye:'A szemkörnyéki formuláknál az irritációs kockázat különösen fontos. Retinal, koffein, peptidek és PDRN bizonyítékát külön értékeljük.',hair:'Különválasztjuk a hajszál kozmetikai kondicionálását a fejbőr- és hajhullás-állításoktól; ezek bizonyítéki szintje eltérő.'}},
 en:{back:'Back to home',title:'CURATED PRODUCTS',lead:'30 products organised by category. We do not build the edit around one brand: we look at formulation, usability and available evidence.',all:'ALL',open:'DETAILED PROFILE',ingredients:'KEY INGREDIENTS / FORMULA FOCUS',detail:'BEAUTY BY ILDY PRODUCT PROFILE',forWhom:'WHO MAY LIKE IT?',why:'WHY IT MADE THE EDIT',science:'WHAT DOES THE SCIENCE SAY?',watch:'IMPORTANT TO KNOW',formula:'FORMULA MAP',buy:'PURCHASE',buyText:'Purchase options will be connected product by product when the final sales channel is ready.',inci:'FULL INCI',inciText:'The complete current INCI is published only after verification against an official manufacturer or package source. We do not infer percentages from ingredient order.',reviewed:'Professional profile · continuously updated',search:'Search by product or brand…',count:'products',categories:{agewell:'AGE-WELL / LINES & FIRMNESS',pdrn:'PDRN & RECOVERY',barrier:'BARRIER & HYDRATION',pigment:'PIGMENTATION',soothe:'SOOTHING & SENSITIVITY',eye:'EYE & LASH',hair:'HAIR & SCALP'},badges:{tested:'PERSONALLY TESTED',selected:'EDITORIAL SELECTION',new:'2026 NEW / CURRENT',premium:'PREMIUM SELECTION',trend:'EARLY / TREND AREA'},scienceText:{agewell:'Retinoids have strong evidence; peptides and botanical complexes vary, so finished products are assessed separately.',pdrn:'Topical PDRN research is promising, but findings cannot be transferred automatically to every PDRN-labelled cosmetic. Source, molecular size, concentration, delivery and finished-product data matter.',barrier:'Ceramides, cholesterol, humectants and soothing agents have well-established roles; formulation balance and tolerability remain decisive.',pigment:'Pigmentation care depends on active choice and consistent sun protection.',soothe:'Soothing botanicals and humectants may help, while potential irritants deserve extra scrutiny in sensitive skin.',eye:'Eye-area formulas require careful irritation assessment. Retinal, caffeine, peptides and PDRN are evaluated separately.',hair:'We distinguish cosmetic conditioning of the hair shaft from scalp and hair-loss claims; the evidence standards differ.'}},
 de:{back:'Zurück zur Startseite',title:'AUSGEWÄHLTE PRODUKTE',lead:'30 Produkte, nach Kategorien geordnet. Die Auswahl ist nicht an eine Marke gebunden: Formulierung, Anwendung und verfügbare Evidenz stehen im Mittelpunkt.',all:'ALLE',open:'DETAILPROFIL',ingredients:'WICHTIGE INHALTSSTOFFE / FORMEL-FOKUS',detail:'BEAUTY BY ILDY PRODUKTPROFIL',forWhom:'FÜR WEN KANN ES INTERESSANT SEIN?',why:'WARUM IN DER AUSWAHL?',science:'WAS SAGT DIE WISSENSCHAFT?',watch:'WICHTIG ZU WISSEN',formula:'FORMEL-LANDKARTE',buy:'KAUFEN',buyText:'Die Kaufoption wird für jedes Produkt aktiviert, sobald der endgültige Vertriebskanal feststeht.',inci:'VOLLSTÄNDIGE INCI',inciText:'Die vollständige aktuelle INCI wird nur nach Prüfung einer offiziellen Hersteller- oder Verpackungsquelle veröffentlicht. Prozentwerte werden nicht aus der Reihenfolge der INCI abgeleitet.',reviewed:'Fachprofil · laufend aktualisiert',search:'Nach Produkt oder Marke suchen…',count:'Produkte',categories:{agewell:'AGE-WELL / FALTEN & FESTIGKEIT',pdrn:'PDRN & REGENERATION',barrier:'BARRIERE & FEUCHTIGKEIT',pigment:'PIGMENTIERUNG',soothe:'BERUHIGUNG & SENSIBILITÄT',eye:'AUGENPARTIE & WIMPERN',hair:'HAAR & KOPFHAUT'},badges:{tested:'PERSÖNLICH GETESTET',selected:'REDAKTIONELLE AUSWAHL',new:'2026 NEU / AKTUELL',premium:'PREMIUM-AUSWAHL',trend:'FRÜHES / TREND-THEMA'},scienceText:{agewell:'Retinoide verfügen über starke Evidenz; bei Peptiden und Pflanzenkomplexen variiert die Datenlage, daher bewerten wir auch das Fertigprodukt separat.',pdrn:'Die Forschung zu topischem PDRN ist vielversprechend, lässt sich aber nicht automatisch auf jedes PDRN-Kosmetikum übertragen. Quelle, Molekülgröße, Konzentration, Delivery und Produktdaten sind wichtig.',barrier:'Ceramide, Cholesterin, Feuchthaltemittel und beruhigende Stoffe haben etablierte Funktionen; Formulierungsbalance und Verträglichkeit bleiben entscheidend.',pigment:'Bei Pigmentierung sind Wirkstoffauswahl und konsequenter Sonnenschutz zentral.',soothe:'Beruhigende Pflanzenstoffe und Feuchthaltemittel können helfen; potenzielle Reizstoffe prüfen wir bei sensibler Haut besonders.',eye:'Bei Augenprodukten ist das Reizpotenzial besonders wichtig. Retinal, Koffein, Peptide und PDRN werden getrennt bewertet.',hair:'Kosmetische Pflege des Haarschafts wird von Kopfhaut- und Haarausfall-Aussagen getrennt; die Evidenzanforderungen sind unterschiedlich.'}}
};

const categoryOrder=['agewell','pdrn','barrier','pigment','soothe','eye','hair'];

export function ProductsPage({lang='hu'}){
 const t=T[lang]||T.hu; const [cat,setCat]=useState('all'); const [q,setQ]=useState('');
 const filtered=useMemo(()=>products.filter(p=>(cat==='all'||p.category===cat)&&(`${p.brand} ${p.name}`.toLowerCase().includes(q.toLowerCase()))),[cat,q]);
 const groups=categoryOrder.map(c=>[c,filtered.filter(p=>p.category===c)]).filter(([,arr])=>arr.length);
 return <main className="productsPage"><section className="productsHero"><div><a className="productBack" href="#top"><ArrowLeft size={14}/>{t.back}</a><p className="eyebrow">BEAUTY BY ILDY</p><h1>{t.title}</h1><p>{t.lead}</p><span>{products.length} {t.count}</span></div></section><div className="productToolbar"><div className="productSearch"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search}/></div><div className="productFilters"><button className={cat==='all'?'active':''} onClick={()=>setCat('all')}>{t.all}</button>{categoryOrder.map(c=><button key={c} className={cat===c?'active':''} onClick={()=>setCat(c)}>{t.categories[c]}</button>)}</div></div><div className="productCategoryWrap">{groups.map(([c,arr])=><section className="productCategory" key={c}><div className="productCategoryHead"><h2>{t.categories[c]}</h2><span>{arr.length}</span></div><div className="productGrid">{arr.map(p=><ProductCard key={p.slug} p={p} t={t}/>)}</div></section>)}</div></main>
}

function ProductCard({p,t}){return <article className="productCard"><div className="productMonogram">{p.brand.slice(0,2)}</div><div className="productCardBody"><div className="productMeta"><span>{t.categories[p.category]}</span><em>{t.badges[p.badge]}</em></div><p className="productBrand">{p.brand}</p><h2>{p.name}</h2><p className="productFocus">{p.ingredients.slice(0,4).join(' · ')}</p><a href={`#product-${p.slug}`}>{t.open}<ArrowRight size={14}/></a></div></article>}

export function ProductDetail({lang='hu',slug}){
 const t=T[lang]||T.hu; const p=products.find(x=>x.slug===slug); if(!p)return <main className="productDetailPage"><section className="detailHero"><div><a className="productBack" href="#products"><ArrowLeft size={14}/>{t.title}</a><h1>Product not found</h1></div></section></main>;
 return <main className="productDetailPage"><section className="detailHero"><div><a className="productBack" href="#products"><ArrowLeft size={14}/>{t.title}</a><p className="eyebrow">{t.detail}</p><p className="detailBrand">{p.brand}</p><h1>{p.name}</h1><div className="detailTags"><span>{t.categories[p.category]}</span><span>{t.badges[p.badge]}</span></div><p className="detailReviewed">{t.reviewed}</p></div></section><section className="detailIntro"><article><CheckCircle2 size={23}/><h2>{t.forWhom}</h2><p>{lang==='hu'?p.forWhom:categoryFallback(p.category,lang)}</p></article><article><Info size={23}/><h2>{t.why}</h2><p>{lang==='hu'?p.why:whyFallback(p,lang)}</p></article></section><section className="detailSection"><div className="detailSectionHead"><Layers3 size={24}/><div><p className="eyebrow">{t.formula}</p><h2>{t.ingredients}</h2></div></div><div className="ingredientPills">{p.ingredients.map(i=><span key={i}>{i}</span>)}</div></section><section className="detailSplit"><article><FlaskConical size={23}/><h2>{t.science}</h2><p>{t.scienceText[p.category]}</p></article><article><Info size={23}/><h2>{t.watch}</h2><p>{lang==='hu'?p.watch:watchFallback(p.category,lang)}</p></article></section><section className="detailSection inciPolicy"><FlaskConical size={24}/><div><h2>{t.inci}</h2><p>{t.inciText}</p></div></section><section className="detailBuy"><h2>{t.buy}</h2><p>{t.buyText}</p></section></main>
}

function categoryFallback(c,lang){const x={en:{agewell:'For an age-well routine focused on lines, firmness and long-term skin quality.',pdrn:'For those interested in PDRN and recovery-focused formulas.',barrier:'For dry, dehydrated or barrier-stressed skin.',pigment:'For uneven tone and dark-spot routines alongside daily sun protection.',soothe:'For sensitive or irritation-prone skin and calming routines.',eye:'For eye-area or lash care with special attention to tolerability.',hair:'For targeted hair-length, ends or scalp care.'},de:{agewell:'Für Age-Well-Routinen mit Fokus auf Linien, Festigkeit und langfristige Hautqualität.',pdrn:'Für alle, die sich für PDRN- und regenerationsorientierte Formeln interessieren.',barrier:'Für trockene, feuchtigkeitsarme oder barrieregestresste Haut.',pigment:'Für ungleichmäßigen Hautton und Pigmentflecken zusammen mit täglichem Sonnenschutz.',soothe:'Für sensible oder reizanfällige Haut und beruhigende Routinen.',eye:'Für Augen- oder Wimpernpflege mit besonderem Blick auf die Verträglichkeit.',hair:'Für gezielte Pflege von Haarlängen, Spitzen oder Kopfhaut.'}};return (x[lang]||x.en)[c]}
function whyFallback(p,lang){return lang==='de'?`Aufgenommen wegen des Formel-Fokus auf ${p.ingredients.slice(0,3).join(', ')} und seiner klaren Rolle innerhalb der Kategorie.`:`Included for its formula focus on ${p.ingredients.slice(0,3).join(', ')} and its clear role within the category.`}
function watchFallback(c,lang){const en={agewell:'Introduce stronger actives gradually and assess irritation risk.',pdrn:'Do not transfer evidence from one PDRN product automatically to another.',barrier:'Tolerability and the balance of the complete formula matter.',pigment:'Consistent sun protection remains essential.',soothe:'Check fragrance and other potential irritants on sensitive skin.',eye:'Use extra caution around the eye area and introduce retinal slowly.',hair:'Separate cosmetic conditioning claims from scalp or hair-loss treatment claims.'};const de={agewell:'Stärkere Wirkstoffe langsam einführen und das Reizpotenzial beachten.',pdrn:'Evidenz eines PDRN-Produkts nicht automatisch auf ein anderes übertragen.',barrier:'Verträglichkeit und Balance der Gesamtformel sind entscheidend.',pigment:'Konsequenter Sonnenschutz bleibt unverzichtbar.',soothe:'Bei sensibler Haut Duftstoffe und andere mögliche Reizstoffe prüfen.',eye:'Im Augenbereich besonders vorsichtig sein und Retinal langsam einführen.',hair:'Kosmetische Pflegeaussagen klar von Kopfhaut- oder Haarausfallbehandlung trennen.'};return (lang==='de'?de:en)[c]}
