import React,{useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,CheckCircle2,FlaskConical,Info,Layers3,Search} from 'lucide-react';
import './products.css';

const P=(slug,brand,name,category,ingredients,badge,forWhom,why,watch)=>({slug,brand,name,category,ingredients,badge,forWhom,why,watch});

export const products=[
P('hubislab-eternal','HUBISLAB','Premium Active Eternal Eye & Face Cream','agewell',['BOTALIX™ / Acmella','peptidek','squalane','panthenol','Centella asiatica'],'tested','Azoknak, akik finom vonalakra, a szemkörnyék célzott ápolására és teltebb, komfortosabb bőrérzetre keresnek prémium arc- és szemkörnyékápoló krémet.','Összetett formula hidratáló, nyugtató és age-well összetevőkkel; személyes használati tapasztalat is kapcsolódik hozzá.','A BOTALIX™-hoz kapcsolódó „botox-hatású” marketinget nem azonosítjuk az injekciós botulinum-toxin kezelésével.'),
P('medicube-pdrn','MEDICUBE','PDRN Pink Hyaluronic Moisturizing Cream','pdrn',['Sodium DNA / PDRN','niacinamide','ceramidok','panthenol','hialuronsav-komplex'],'selected','Azoknak, akik hidratáló-regeneráló krémet keresnek, és a PDRN mellett a bőrbarrier támogatása is fontos számukra.','Jó példa arra, hogyan érdemes egy PDRN-terméket a teljes formula alapján értékelni, nem csak egyetlen kiemelt összetevő alapján.','A Sodium DNA/PDRN mennyiségét csak hivatalosan igazolt adat alapján tüntetjük fel.'),
P('iope-xmd-stem-iii','IOPE','XMD Stem III Clinical Recovery Serum','pdrn',['PDRN / DNA-komplex','hialuronsav','Centella-komponensek','peptid'],'new','Azoknak, akik prémium regeneráló szérumot keresnek, és a hidratálást age-well fókuszú formulával szeretnék kombinálni.','Fejlesztésközpontú koncepció többféle hidratáló és hatóanyag-bejuttatást támogató összetevővel.','A gyártói klinikai eredményeket külön kezeljük a független tudományos szakirodalomtól.'),
P('iope-retinol-rx-2','IOPE','Retinol RX 2% Reti-jection Serum','agewell',['retinoid-komplex','retinol','spicule delivery'],'new','Azoknak, akik már ismerik a retinoidokat, és fokozatosan szeretnének erősebb age-well formulát bevezetni.','Retinoidokat és spicule-alapú bejuttatási koncepciót kapcsol össze, ezért jól illik a skincare és beauty-tech határterületéhez.','A „2%” megjelölést nem értelmezzük automatikusan 2% tiszta retinolként; fokozatos bevezetés szükséges.'),
P('aestura-atobarrier365-cream','AESTURA','Atobarrier365 Cream','barrier',['Ceramide NP','cholesterol','squalane','phytosphingosine'],'selected','Azoknak, akik száraz, érzékenyebb vagy sérült bőrbarrierre keresnek lipidpótló krémet.','Klasszikus barrier-lipid logikára épülő formula ceramiddal, koleszterinnel, szkvalánnal és fitoszfingozinnal.','Az egyéni tolerancia és a teljes INCI továbbra is fontos.'),
P('aestura-hydro-soothing-cream','AESTURA','Atobarrier365 Hydro Soothing Cream','barrier',['ceramidok','hialuronsav','niacinamide','nyugtató hidratálók'],'new','Azoknak, akik vízhiányos vagy érzékenyebb bőrre keresnek könnyebb textúrájú hidratálót.','A barrier-vonal könnyedebb, hidratálásra és komfortérzetre hangolt alternatívája.','Az aktuális formulát és a regionális INCI-t külön ellenőrizzük.'),
P('aestura-cera-ha-serum','AESTURA','Atobarrier365 Hydro Cera-HA Serum','barrier',['ceramidok','hialuronsav-komplex','humektánsok'],'selected','Azoknak, akik könnyen rétegezhető hidratáló-barrier szérumot keresnek.','A ceramidok és a hialuronsav kombinációja miatt jól illeszthető szárazabb és vízhiányos bőr ápolásába.','A hidratáló hatást a teljes formula, annak arányai és tolerálhatósága határozza meg.'),
P('biodance-caviar-pdrn-capsule-cream','BIODANCE','Rejuvenating Caviar PDRN Capsule Cream','pdrn',['PDRN-vonal','hidratálók','emolliensek'],'new','Azoknak, akik gazdagabb textúrájú, PDRN-fókuszú regeneráló krémet keresnek.','A kapszulás textúra és a PDRN-koncepció miatt érdekes, modern formulavilágot képvisel.','A „caviar PDRN” elnevezés önmagában nem bizonyít nagyobb biológiai hatást.'),
P('biodance-caviar-pdrn-bubble-booster','BIODANCE','Caviar PDRN Liposome Bubble Booster','pdrn',['PDRN-vonal','liposzómás delivery','hidratálók'],'new','Azoknak, akik könnyű booster-lépést keresnek PDRN-fókuszú rutinba.','A liposzómás bejuttatási koncepció miatt edukációs szempontból is érdekes.','A liposzóma jelenléte önmagában nem bizonyít nagyobb bőrbejutást.'),
P('biodance-caviar-pdrn-toner-pad','BIODANCE','Caviar PDRN Dual Gel Toner Pad','pdrn',['PDRN-vonal','hidratáló gélrendszer'],'new','Azoknak, akik gyors, kényelmes és hidratáló tonerpados lépést keresnek.','Jól mutatja, hogyan jelenik meg a PDRN különböző kozmetikai formátumokban.','Érzékeny bőrön a mechanikai dörzsölés irritáló lehet.'),
P('biodance-caviar-pdrn-eye-patch','BIODANCE','Caviar PDRN Eye Patch','eye',['PDRN-vonal','hidratálók'],'new','Azoknak, akik rövid távú hidratálást és komfortosabb szemkörnyéki érzetet szeretnének.','Kiegészítő, élményközpontú termék a PDRN-vonalban.','A szempatch rövid távú hidratáló hatása nem azonos tartós ránccsökkentéssel.'),
P('sulwhasoo-ginseng-cream','SULWHASOO','Concentrated Ginseng Rejuvenating Cream','agewell',['ginseng / ginszenozidok','peptidek','antioxidánsok','emolliensek'],'premium','Azoknak, akik gazdagabb textúrájú, luxus age-well krémet keresnek.','Komplex prémium formula erős márka-K+F háttérrel és ginseng-fókusszal.','A ginsenggel kapcsolatos kutatásokat különválasztjuk a késztermék gyártói vizsgálataitól.'),
P('sulwhasoo-ginseng-serum','SULWHASOO','Concentrated Ginseng Rejuvenating Serum','agewell',['ginseng / ginszenozidok','antioxidánsok','hidratálók'],'premium','Azoknak, akik könnyebb textúrájú, prémium age-well szérumot keresnek.','A ginseng-vonal szérumos, jól rétegezhető alternatívája.','A prémium ár önmagában nem a hatékonyság bizonyítéka.'),
P('genabelle-pdrn-cream','GENABELLE','PDRN Rejuvenating Cream','pdrn',['PDRN / Sodium DNA','hidratálók','barrier-támogatók'],'selected','Azoknak, akik PDRN mellett krémes hidratálást és bőrbarrier-támogatást is szeretnének.','Jól értelmezhető PDRN + hidratálás irány.','A pontos Sodium DNA mennyiséget és a teljes formulát ellenőrzött forrásból rögzítjük.'),
P('genabelle-pdrn-hyper-boost','GENABELLE','PDRN 3% Hyper Boost Ampoule','pdrn',['PDRN / Sodium DNA','humektánsok','nyugtató összetevők'],'selected','Azoknak, akik könnyű, koncentrált PDRN-ampullát keresnek hidratáló vagy barrier-rutinba.','A jelenlegi Genabelle PDRN-vonal koncentráltabb ampullás tagja.','A 3% megjelölést a terméknév részeként kezeljük; az aktuális INCI-t hivatalos forrásból ellenőrizzük.'),
P('axis-y-triple-pdrn','AXIS-Y','Triple PDRN Barrier Boost Serum','pdrn',['Sodium DNA / növényi PDRN-koncepció','panthenol','NAD+','sh-Oligopeptide-1'],'new','Azoknak, akik újgenerációs, barrier-fókuszú szérumot keresnek PDRN-, NAD+- és peptidkoncepcióval.','Jó példája a 2026-os többfunkciós formulatrendnek.','A növényi PDRN és a topikális NAD+ kozmetikai bizonyítékait korai, ígéretes területként kezeljük.'),
P('axis-y-panthenol-10','AXIS-Y','Panthenol 10 Skin Smoothing Shield Cream','barrier',['panthenol','barrier-támogató lipidek','nyugtató összetevők'],'selected','Azoknak, akik érzékenyebb, húzódó vagy barrier-terhelt bőrre keresnek nyugtató krémet.','Magas panthenol-fókuszú, könnyen értelmezhető barrier-formula.','A 10% panthenol mellett is a teljes formula és az egyéni tolerancia döntő.'),
P('axis-y-dark-spot','AXIS-Y','Dark Spot Correcting Glow Serum','pigment',['niacinamide','növényi kivonatok','hidratálók'],'selected','Azoknak, akik egyenetlen bőrtónus és pigmentfoltok támogatására keresnek könnyen rétegezhető szérumot.','Niacinamid-fókuszú, egyszerűen beilleszthető pigmentációs opció.','A következetes fényvédelem a pigmentációs rutin alapja.'),
P('skin1004-centella-ampoule','SKIN1004','Madagascar Centella Ampoule','soothe',['Centella asiatica kivonat'],'selected','Azoknak, akik minimalista, nyugtató formulát keresnek érzékenyebb vagy irritációra hajlamos bőrre.','Jó példa arra, hogy egy egyszerű formula is lehet tudatos választás.','Érzékeny bőrön érdemes először kis bőrfelületen kipróbálni.'),
P('skin1004-probio-cica','SKIN1004','Probio-Cica Intensive Ampoule','barrier',['fermentált Centella-komplex','ceramid/barrier fókusz','humektánsok'],'selected','Azoknak, akik érzékenyebb bőrre keresnek gazdagabb, barrier-támogató szérumot.','A Centella-vonalat barrier-fókuszú összetevőkkel kapcsolja össze.','A fermentált összetevők sem jelentenek automatikusan jobb tolerálhatóságot.'),
P('anua-pdrn-ha-serum','ANUA','PDRN Hyaluronic Acid Capsule 100 Serum','pdrn',['PDRN-vonal','hialuronsav-komplex','hidratálók'],'selected','Azoknak, akik hidratálásközpontú PDRN-szérumot keresnek.','A PDRN-koncepciót többféle hidratáló összetevővel kapcsolja össze.','A „100” a terméknév része; nem kezeljük automatikusan koncentrációként.'),
P('haruharu-rose-pdrn','HARUHARU WONDER','Rose PDRN Firming Serum','pdrn',['PDRN-koncepció','rose complex','hidratálók'],'selected','Azoknak, akik könnyebb, feszességre pozicionált PDRN-szérumot keresnek.','Érdekes alternatív PDRN-koncepció hidratáló komponensekkel.','A növényi eredetű DNS-fragmentumok klinikai egyenértékűségét nem feltételezzük.'),
P('haruharu-nad-mist','HARUHARU WONDER','Black Rice Probiotics Barrier 2% NAD+ Serum Mist','barrier',['NAD+','black rice','probiotikus/fermentált összetevők','hidratálók'],'trend','Azoknak, akik kényelmes barrier-mistet és új hatóanyagkoncepciót keresnek.','A NAD+ miatt különösen érdekes edukációs és trendfigyelő termék.','A topikális NAD+ kozmetikai bizonyítéka még korai; nem kommunikáljuk „sejtfiatalítóként”.'),
P('medipeel-phyto-ex-pdrn-eye','MEDI-PEEL','Phyto Ex PDRN Eye Cream','eye',['PDRN-koncepció','peptidek','exoszóma-marketinggel társított összetevők'],'selected','Azoknak, akik összetettebb szemkörnyékápolót keresnek peptidekkel és PDRN-koncepcióval.','Jó kritikai elemzési példa a PDRN + exoszóma trend miatt.','Az „exoszóma” kifejezést különösen szigorúan ellenőrizzük; nem minden ilyen marketingállítás jelent karakterizált exoszómát.'),
P('thesaem-aloe-99','THE SAEM','Jeju Fresh Aloe 99% Soothing Gel','soothe',['Aloe barbadensis leaf extract','glycerin','növényi kivonatok'],'tested','Azoknak, akik egyszerű, multifunkcionális nyugtató-hidratáló gélt keresnek arcra vagy testre.','Jó ár-érték arányú, személyesen is kipróbált, könnyen érthető termék.','Érzékeny bőrön az illatanyagokat és más lehetséges irritáló összetevőket is figyelembe kell venni.'),
P('nature-republic-argan-hair','NATURE REPUBLIC','Argan Essential Deep Care Hair Essence','hair',['argánolaj','szilikonos hajsimító rendszer','emolliensek'],'tested','Azoknak, akik száraz, fénytelen hajhosszra és hajvégekre keresnek simító, fényfokozó hajesszenciát.','Személyesen bevált termék, gyorsan érzékelhető kozmetikai hatással a hajhosszon.','A hajszál felszíni simítása nem azonos a hajhullás vagy a hajhagymák kezelésével.'),
P('floland-eyelash-serum','FLOLAND','Nutrition Eyelash Serum','eye',['peptidek','protein-komplex','kondicionáló összetevők'],'tested','Azoknak, akik törékenyebb, szárazabb szempillák kondicionálására keresnek szérumot.','Személyesen ajánlott termék peptid- és proteinfókuszú formulával.','A szempillák dúsabbnak tűnő megjelenése nem azonos gyógyszeres szempillanövesztő hatással.'),
P('labo-h-scalp-strengthening','LABO-H','Scalp Strengthening Hair Loss Care Shampoo','hair',['fejbőr-fókuszú tisztító rendszer','kondicionálók','növényi összetevők'],'selected','Azoknak, akik fejbőr-fókuszú sampont keresnek hajápolási rutinjukba.','Jól illeszkedik a haj- és fejbőrápolási kategóriába, ahol a fejbőr komfortja külön fókuszt kap.','A fejbőr komfortjára vonatkozó kozmetikai állításokat különválasztjuk a hajhullás kezelésére vonatkozó bizonyítékoktól.'),
P('mise-en-scene-perfect-serum','MISE-EN-SCÈNE','Perfect Serum','hair',['hajsimító olaj/emolliens rendszer','szilikonok','növényi olajok'],'selected','Azoknak, akik fényesebb, simább hajhosszt szeretnének, különösen száraz hajvégeken.','Klasszikus koreai hajszérum-kategória, jól érzékelhető kozmetikai hatással.','A szilikonok funkcionális hajsimító összetevők; a felhalmozódás mértéke egyéni lehet.'),
P('abib-pdrn-retinal-eye-patch','ABIB','PDRN Retinal Eye Patch Glow Jelly','eye',['Sodium DNA','retinal','niacinamide','panthenol','squalane','caffeine'],'new','Azoknak, akik már ismerik a retinoidokat, és retinalt tartalmazó szemkörnyékápolót keresnek.','A retinal, a PDRN-koncepció és a koffein kombinációja miatt többcélú, érdekes formula.','A retinal a szemkörnyéken irritálhat; a használat gyakoriságát fokozatosan érdemes kialakítani.')
];

const T={
 hu:{back:'Vissza a főoldalra',title:'VÁLOGATOTT TERMÉKEK',lead:'30 termék, átlátható kategóriákba rendezve. Nem egyetlen márkára építünk: a formulát, a használhatóságot és a rendelkezésre álló tudományos bizonyítékot együtt nézzük.',all:'MIND',open:'RÉSZLETES ADATLAP',ingredients:'FŐ ÖSSZETEVŐK / FORMULA-FÓKUSZ',detail:'BEAUTY BY ILDY TERMÉKADATLAP',forWhom:'KINEK ÉS MIRE AJÁNLJUK?',why:'MIÉRT KERÜLT A VÁLOGATÁSBA?',science:'MIT MOND A TUDOMÁNY?',watch:'FONTOS TUDNI',formula:'FORMULA TÉRKÉP',buy:'VÁSÁRLÁS',buyText:'A vásárlási lehetőséget termékenként kapcsoljuk be, amikor a végleges értékesítési csatorna rendelkezésre áll.',inci:'TELJES INCI',inciText:'A teljes, aktuális INCI-t kizárólag ellenőrzött gyártói vagy csomagolási adat alapján tesszük közzé. Koncentrációt nem következtetünk az INCI sorrendjéből.',reviewed:'Szakmai adatlap · folyamatosan frissítve',search:'Keresés termék vagy márka szerint…',count:'termék',notFound:'A termék nem található.',categories:{agewell:'AGE-WELL / RÁNC & FESZESSÉG',pdrn:'PDRN & REGENERÁCIÓ',barrier:'BARRIER & HIDRATÁLÁS',pigment:'PIGMENTÁCIÓ',soothe:'NYUGTATÁS & ÉRZÉKENYSÉG',eye:'SZEMKÖRNYÉK & SZEMPILLA',hair:'HAJ & FEJBŐR'},badges:{tested:'SZEMÉLYESEN TESZTELT',selected:'SZAKMAI VÁLOGATÁS',new:'2026 ÚJDONSÁG / AKTUÁLIS',premium:'PRÉMIUM VÁLOGATÁS',trend:'KORAI / TRENDTERÜLET'},scienceText:{agewell:'A retinoidok mögött erős bizonyíték áll; peptideknél és növényi komplexeknél az evidenciaszint változó, ezért a készterméket külön is vizsgáljuk.',pdrn:'A topikális PDRN humán kutatása ígéretes, de az eredmények nem általánosíthatók minden PDRN-termékre. A forrás, a molekulaméret, a koncentráció, a hatóanyag-bejuttatás és a késztermékre vonatkozó adatok egyaránt számítanak.',barrier:'A ceramidok, a koleszterin, a humektánsok és a nyugtató összetevők szerepe jól ismert; a teljes formula és a tolerálhatóság azonban döntő.',pigment:'Pigmentáció esetén az aktív összetevő mellett a következetes fényvédelem is alapvető.',soothe:'A nyugtató növényi kivonatok és hidratálók segíthetnek, de érzékeny bőrnél az esetleges irritáló összetevőket külön is ellenőrizzük.',eye:'A szemkörnyéki formuláknál különösen fontos az irritációs kockázat. A retinal, a koffein, a peptidek és a PDRN bizonyítékait külön értékeljük.',hair:'Különválasztjuk a hajszál kozmetikai kondicionálását a fejbőrre vagy hajhullásra vonatkozó állításoktól, mert ezek bizonyítéki szintje eltérő.'}},
 en:{back:'Back to home',title:'CURATED PRODUCTS',lead:'30 products organised into clear categories. We do not build the selection around a single brand: formulation, usability and available evidence are considered together.',all:'ALL',open:'DETAILED PROFILE',ingredients:'KEY INGREDIENTS / FORMULA FOCUS',detail:'BEAUTY BY ILDY PRODUCT PROFILE',forWhom:'WHO IS IT FOR?',why:'WHY IT MADE THE SELECTION',science:'WHAT DOES THE SCIENCE SAY?',watch:'IMPORTANT TO KNOW',formula:'FORMULA MAP',buy:'PURCHASE',buyText:'Purchase options will be connected product by product once the final sales channel is ready.',inci:'FULL INCI',inciText:'The complete current INCI is published only after verification against an official manufacturer or packaging source. We do not infer percentages from ingredient order.',reviewed:'Professional profile · continuously updated',search:'Search by product or brand…',count:'products',notFound:'Product not found.',categories:{agewell:'AGE-WELL / LINES & FIRMNESS',pdrn:'PDRN & RECOVERY',barrier:'BARRIER & HYDRATION',pigment:'PIGMENTATION',soothe:'SOOTHING & SENSITIVITY',eye:'EYE & LASH',hair:'HAIR & SCALP'},badges:{tested:'PERSONALLY TESTED',selected:'EDITORIAL SELECTION',new:'2026 NEW / CURRENT',premium:'PREMIUM SELECTION',trend:'EARLY / TREND AREA'},scienceText:{agewell:'Retinoids have strong evidence; evidence for peptides and botanical complexes varies, so finished products are assessed separately.',pdrn:'Topical PDRN research is promising, but findings cannot automatically be transferred to every PDRN-labelled cosmetic. Source, molecular size, concentration, delivery and finished-product data all matter.',barrier:'Ceramides, cholesterol, humectants and soothing agents have well-established roles; the balance and tolerability of the full formulation remain decisive.',pigment:'In pigmentation care, consistent sun protection is essential alongside the chosen active ingredients.',soothe:'Soothing botanicals and humectants may help, while potential irritants deserve extra scrutiny in sensitive skin.',eye:'Eye-area formulas require careful irritation assessment. Evidence for retinal, caffeine, peptides and PDRN is considered separately.',hair:'We distinguish cosmetic conditioning of the hair shaft from scalp or hair-loss claims because the evidence standards differ.'}},
 de:{back:'Zurück zur Startseite',title:'AUSGEWÄHLTE PRODUKTE',lead:'30 Produkte, übersichtlich nach Kategorien geordnet. Die Auswahl ist nicht an eine einzelne Marke gebunden: Formulierung, Anwendung und verfügbare Evidenz werden gemeinsam bewertet.',all:'ALLE',open:'DETAILPROFIL',ingredients:'WICHTIGE INHALTSSTOFFE / FORMEL-FOKUS',detail:'BEAUTY BY ILDY PRODUKTPROFIL',forWhom:'FÜR WEN UND WOFÜR GEEIGNET?',why:'WARUM IN DER AUSWAHL?',science:'WAS SAGT DIE WISSENSCHAFT?',watch:'WICHTIG ZU WISSEN',formula:'FORMEL-LANDKARTE',buy:'KAUFEN',buyText:'Die Kaufoption wird für jedes Produkt aktiviert, sobald der endgültige Vertriebskanal feststeht.',inci:'VOLLSTÄNDIGE INCI',inciText:'Die vollständige aktuelle INCI wird nur nach Prüfung einer offiziellen Hersteller- oder Verpackungsquelle veröffentlicht. Prozentwerte werden nicht aus der Reihenfolge der INCI abgeleitet.',reviewed:'Fachprofil · laufend aktualisiert',search:'Nach Produkt oder Marke suchen…',count:'Produkte',notFound:'Produkt nicht gefunden.',categories:{agewell:'AGE-WELL / FALTEN & FESTIGKEIT',pdrn:'PDRN & REGENERATION',barrier:'BARRIERE & FEUCHTIGKEIT',pigment:'PIGMENTIERUNG',soothe:'BERUHIGUNG & SENSIBILITÄT',eye:'AUGENPARTIE & WIMPERN',hair:'HAAR & KOPFHAUT'},badges:{tested:'PERSÖNLICH GETESTET',selected:'REDAKTIONELLE AUSWAHL',new:'2026 NEU / AKTUELL',premium:'PREMIUM-AUSWAHL',trend:'FRÜHES / TREND-THEMA'},scienceText:{agewell:'Retinoide verfügen über eine starke Evidenz; bei Peptiden und Pflanzenkomplexen variiert die Datenlage, daher bewerten wir auch das Fertigprodukt separat.',pdrn:'Die Forschung zu topischem PDRN ist vielversprechend, lässt sich aber nicht automatisch auf jedes PDRN-Kosmetikum übertragen. Quelle, Molekülgröße, Konzentration, Delivery und Produktdaten sind wichtig.',barrier:'Ceramide, Cholesterin, Feuchthaltemittel und beruhigende Stoffe haben etablierte Funktionen; die Balance und Verträglichkeit der Gesamtformulierung bleiben entscheidend.',pigment:'Bei Pigmentierung sind Wirkstoffauswahl und konsequenter Sonnenschutz gleichermaßen wichtig.',soothe:'Beruhigende Pflanzenstoffe und Feuchthaltemittel können helfen; potenzielle Reizstoffe prüfen wir bei sensibler Haut besonders sorgfältig.',eye:'Bei Produkten für die Augenpartie ist das Reizpotenzial besonders wichtig. Retinal, Koffein, Peptide und PDRN werden getrennt bewertet.',hair:'Wir trennen die kosmetische Pflege des Haarschafts klar von Aussagen zu Kopfhaut oder Haarausfall, da hierfür unterschiedliche Evidenzanforderungen gelten.'}}
};

const categoryOrder=['agewell','pdrn','barrier','pigment','soothe','eye','hair'];

export function ProductsPage({lang='hu'}){
 const t=T[lang]||T.hu; const [cat,setCat]=useState('all'); const [q,setQ]=useState('');
 const filtered=useMemo(()=>products.filter(p=>(cat==='all'||p.category===cat)&&(`${p.brand} ${p.name}`.toLowerCase().includes(q.toLowerCase()))),[cat,q]);
 const groups=categoryOrder.map(c=>[c,filtered.filter(p=>p.category===c)]).filter(([,arr])=>arr.length);
 return <main className="productsPage"><section className="productsHero"><div><a className="productBack" href="#top"><ArrowLeft size={14}/>{t.back}</a><p className="eyebrow">BEAUTY BY ILDY</p><h1>{t.title}</h1><p>{t.lead}</p><span>{products.length} {t.count}</span></div></section><div className="productToolbar"><div className="productSearch"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search}/></div><div className="productFilters"><button className={cat==='all'?'active':''} onClick={()=>setCat('all')}>{t.all}</button>{categoryOrder.map(c=><button key={c} className={cat===c?'active':''} onClick={()=>setCat(c)}>{t.categories[c]}</button>)}</div></div><div className="productCategoryWrap">{groups.map(([c,arr])=><section className="productCategory" key={c}><div className="productCategoryHead"><h2>{t.categories[c]}</h2><span>{arr.length}</span></div><div className="productGrid">{arr.map(p=><ProductCard key={p.slug} p={p} t={t}/>)}</div></section>)}</div></main>
}

function ProductCard({p,t}){return <article className="productCard"><div className="productMonogram">{p.brand.slice(0,2)}</div><div className="productCardBody"><div className="productMeta"><span>{t.categories[p.category]}</span><em>{t.badges[p.badge]}</em></div><p className="productBrand">{p.brand}</p><h2>{p.name}</h2><p className="productFocus">{p.ingredients.slice(0,4).join(' · ')}</p><a href={`#product-${p.slug}`}>{t.open}<ArrowRight size={14}/></a></div></article>}

export function ProductDetail({lang='hu',slug}){
 const t=T[lang]||T.hu; const p=products.find(x=>x.slug===slug); if(!p)return <main className="productDetailPage"><section className="detailHero"><div><a className="productBack" href="#products"><ArrowLeft size={14}/>{t.title}</a><h1>{t.notFound}</h1></div></section></main>;
 return <main className="productDetailPage"><section className="detailHero"><div><a className="productBack" href="#products"><ArrowLeft size={14}/>{t.title}</a><p className="eyebrow">{t.detail}</p><p className="detailBrand">{p.brand}</p><h1>{p.name}</h1><div className="detailTags"><span>{t.categories[p.category]}</span><span>{t.badges[p.badge]}</span></div><p className="detailReviewed">{t.reviewed}</p></div></section><section className="detailIntro"><article><CheckCircle2 size={23}/><h2>{t.forWhom}</h2><p>{lang==='hu'?p.forWhom:categoryFallback(p.category,lang)}</p></article><article><Info size={23}/><h2>{t.why}</h2><p>{lang==='hu'?p.why:whyFallback(p,lang)}</p></article></section><section className="detailSection"><div className="detailSectionHead"><Layers3 size={24}/><div><p className="eyebrow">{t.formula}</p><h2>{t.ingredients}</h2></div></div><div className="ingredientPills">{p.ingredients.map(i=><span key={i}>{i}</span>)}</div></section><section className="detailSplit"><article><FlaskConical size={23}/><h2>{t.science}</h2><p>{t.scienceText[p.category]}</p></article><article><Info size={23}/><h2>{t.watch}</h2><p>{lang==='hu'?p.watch:watchFallback(p.category,lang)}</p></article></section><section className="detailSection inciPolicy"><FlaskConical size={24}/><div><h2>{t.inci}</h2><p>{t.inciText}</p></div></section><section className="detailBuy"><h2>{t.buy}</h2><p>{t.buyText}</p></section></main>
}

function categoryFallback(c,lang){const x={en:{agewell:'For people looking for an age-well routine focused on lines, firmness and long-term skin quality.',pdrn:'For people interested in PDRN and recovery-focused formulas.',barrier:'For dry, dehydrated or barrier-stressed skin.',pigment:'For uneven tone and dark-spot routines alongside daily sun protection.',soothe:'For sensitive or irritation-prone skin and calming routines.',eye:'For eye-area or lash care with special attention to tolerability.',hair:'For targeted care of hair lengths, ends or scalp.'},de:{agewell:'Für alle, die eine Age-Well-Routine mit Fokus auf Linien, Festigkeit und langfristige Hautqualität suchen.',pdrn:'Für alle, die sich für PDRN- und regenerationsorientierte Formeln interessieren.',barrier:'Für trockene, feuchtigkeitsarme oder barrieregestresste Haut.',pigment:'Für ungleichmäßigen Hautton und Pigmentflecken in Kombination mit täglichem Sonnenschutz.',soothe:'Für sensible oder reizanfällige Haut und beruhigende Routinen.',eye:'Für die Pflege der Augenpartie oder Wimpern mit besonderem Blick auf die Verträglichkeit.',hair:'Für die gezielte Pflege von Haarlängen, Spitzen oder Kopfhaut.'}};return (x[lang]||x.en)[c]}
function whyFallback(p,lang){return lang==='de'?`Ausgewählt wegen des Formel-Fokus auf ${p.ingredients.slice(0,3).join(', ')} und seiner klaren Rolle innerhalb der Kategorie.`:`Selected for its formula focus on ${p.ingredients.slice(0,3).join(', ')} and its clear role within the category.`}
function watchFallback(c,lang){const en={agewell:'Introduce stronger actives gradually and monitor irritation.',pdrn:'Do not automatically transfer evidence from one PDRN product to another.',barrier:'Tolerability and the balance of the complete formulation matter.',pigment:'Consistent sun protection remains essential.',soothe:'Check fragrance and other potential irritants on sensitive skin.',eye:'Use extra caution around the eye area and introduce retinal gradually.',hair:'Keep cosmetic conditioning claims separate from scalp or hair-loss treatment claims.'};const de={agewell:'Stärkere Wirkstoffe langsam einführen und auf Reizungen achten.',pdrn:'Evidenz eines PDRN-Produkts nicht automatisch auf ein anderes übertragen.',barrier:'Verträglichkeit und Balance der Gesamtformulierung sind entscheidend.',pigment:'Konsequenter Sonnenschutz bleibt unverzichtbar.',soothe:'Bei sensibler Haut Duftstoffe und andere mögliche Reizstoffe prüfen.',eye:'Im Augenbereich besonders vorsichtig sein und Retinal langsam einführen.',hair:'Kosmetische Pflegeaussagen klar von Aussagen zur Behandlung von Kopfhaut oder Haarausfall trennen.'};return (lang==='de'?de:en)[c]}
