import React from 'react';
import {ArrowLeft,ArrowRight,AlertTriangle} from 'lucide-react';
import './product.css';

const txt={
 hu:{back:'Vissza a főoldalra',eye:'BEAUTY BY ILDY TERMÉKELEMZÉS',brand:'MEDICUBE',name:'PDRN Pink Hyaluronic Moisturizing Cream',lead:'Hidratáló és barrier-támogató formula PDRN/Sodium DNA, niacinamide, panthenol, ceramidok, koleszterin, fitoszfingozin, peptidek és többféle hialuronsav-forma kombinációjával.',verdict:'BEAUTY BY ILDY ÖSSZKÉP',verdictText:'Erős hidratáló és barrier-váz. A PDRN ígéretes kutatási terület, de az összetevőre vonatkozó bizonyíték nem bizonyítja automatikusan a késztermék klinikai hatásosságát.',inside:'MI VAN BENNE?',science:'MIT MOND A TUDOMÁNY?',scienceText:'2026-ban humán split-face vizsgálat jelent meg egy meghatározott topikális PDRN-formulával. Ez ígéretes, de az eredmény más formulára nem vihető át automatikusan.',inci:'TELJES INCI',note:'A formulák változhatnak; használat előtt mindig ellenőrizd a csomagoláson lévő aktuális INCI-listát.',buy:'VÁSÁRLÁS',buyText:'A vásárlási lehetőséget a végleges értékesítési csatorna kiválasztása után kapcsoljuk be.'},
 en:{back:'Back to home',eye:'BEAUTY BY ILDY PRODUCT ANALYSIS',brand:'MEDICUBE',name:'PDRN Pink Hyaluronic Moisturizing Cream',lead:'A hydrating, barrier-supporting formula combining PDRN/Sodium DNA, niacinamide, panthenol, ceramides, cholesterol, phytosphingosine, peptides and multiple hyaluronic-acid forms.',verdict:'BEAUTY BY ILDY VERDICT',verdictText:'A strong hydration and barrier base. PDRN is promising, but ingredient-level evidence does not automatically prove finished-product efficacy.',inside:'WHAT IS INSIDE?',science:'WHAT DOES THE SCIENCE SAY?',scienceText:'A 2026 human split-face study evaluated a defined topical PDRN formula. The signal is promising, but the findings cannot automatically be transferred to a different product.',inci:'FULL INCI',note:'Formulations can change; always check the current ingredient list on the package.',buy:'PURCHASE',buyText:'Purchase will be enabled after the final sales channel is selected.'},
 de:{back:'Zurück zur Startseite',eye:'BEAUTY BY ILDY PRODUKTANALYSE',brand:'MEDICUBE',name:'PDRN Pink Hyaluronic Moisturizing Cream',lead:'Eine feuchtigkeitsspendende, barrierestützende Formel mit PDRN/Sodium DNA, Niacinamid, Panthenol, Ceramiden, Cholesterin, Phytosphingosin, Peptiden und mehreren Hyaluronsäure-Formen.',verdict:'BEAUTY BY ILDY FAZIT',verdictText:'Starke Feuchtigkeits- und Barrierbasis. PDRN ist vielversprechend, doch Wirkstoff-Evidenz beweist nicht automatisch die Wirksamkeit des Fertigprodukts.',inside:'WAS IST ENTHALTEN?',science:'WAS SAGT DIE WISSENSCHAFT?',scienceText:'2026 untersuchte eine Human-Split-Face-Studie eine definierte topische PDRN-Formel. Das Signal ist vielversprechend, lässt sich aber nicht automatisch auf ein anderes Produkt übertragen.',inci:'VOLLSTÄNDIGE INCI',note:'Formulierungen können sich ändern; bitte immer die aktuelle Zutatenliste auf der Verpackung prüfen.',buy:'KAUF',buyText:'Die Kaufoption wird nach Auswahl des endgültigen Vertriebskanals aktiviert.'}
};

const formula=['PDRN / Sodium DNA','Niacinamide','Panthenol','Ceramides NP/NS/AS/AP/EOP','Cholesterol','Phytosphingosine','Hyaluronic-acid complex','Peptides','Centella asiatica','Adenosine'];
const INCI='Water, Glycereth-26, Butylene Glycol, Caprylic/Capric Triglyceride, Cyclopentasiloxane, 1,2-Hexanediol, Niacinamide, Hydrogenated Polydecene, Isononyl Isononanoate, Cetearyl Olivate, Ethylhexyl Olivate, Glycerin, Sorbitan Olivate, Sodium DNA, Sodium Acrylates Copolymer, Sodium Polyacryloyldimethyl Taurate, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Polyglyceryl-4 Oleate, Disodium EDTA, Betaine, Panthenol, Fragrance, Ethylhexylglycerin, Adenosine, Sorbitan Isostearate, Limnanthes Alba Seed Oil, Glyceryl Acrylate/Acrylic Acid Copolymer, Citric Acid, Cyanocobalamin, Hydrogenated Lecithin, Cetearyl Alcohol, Stearic Acid, Sodium Hyaluronate, Hydroxypropyltrimonium Hyaluronate, Ceramide NP, Prunella Vulgaris Extract, Fucus Vesiculosus Extract, Morinda Citrifolia Fruit Extract, Momordica Charantia Fruit Extract, Hibiscus Esculentus Fruit Extract, Ceramide NS, Sodium Acetylated Hyaluronate, Hydrolyzed Hyaluronic Acid, Centella Asiatica Leaf Extract, Cholesterol, Phytosphingosine, Ceramide AS, Ceramide AP, Hyaluronic Acid, Copper Tripeptide-1, Sodium Hyaluronate Crosspolymer, Acetyl Hexapeptide-8, Palmitoyl Pentapeptide-4, Hydrolyzed Sodium Hyaluronate, Palmitoyl Tetrapeptide-7, Palmitoyl Tripeptide-1, Potassium Hyaluronate, Ceramide EOP';

export function MedicubePdrnProduct({lang='hu'}){
 const t=txt[lang]||txt.hu;
 return <main className="productPage">
  <section className="productHero"><div><a className="productBack" href="#top"><ArrowLeft size={14}/>{t.back}</a><p className="productEyebrow">{t.eye}</p><p className="productBrand">{t.brand}</p><h1>{t.name}</h1><p className="productLead">{t.lead}</p></div></section>
  <section className="productVerdict"><p>{t.verdict}</p><h2>{t.verdictText}</h2></section>
  <section className="productSection"><h2>{t.inside}</h2><div className="formulaCards">{formula.map(x=><article key={x}><h3>{x}</h3></article>)}</div></section>
  <section className="productScience"><AlertTriangle size={22}/><div><h2>{t.science}</h2><p>{t.scienceText}</p></div></section>
  <section className="productSection"><h2>{t.inci}</h2><p>{INCI}</p><small>{t.note}</small></section>
  <section className="productBuy"><h2>{t.buy}</h2><p>{t.buyText}</p><a href="#top">BEAUTY BY ILDY <ArrowRight size={14}/></a></section>
 </main>;
}
